'use client';
import Link from 'next/link';
import { getProjects, getDocs } from '@/lib/content';
import { OSS_PORTFOLIO_GROUPS } from '@/lib/oss';

type Locale='ko'|'en';
export default function OssHub({locale}:{locale:Locale}){
 const projects=getProjects(locale), docs=getDocs(locale), groups=OSS_PORTFOLIO_GROUPS;
 const bySlug=new Map(projects.map(p=>[p.slug,p])); const docsByProject=new Map<string,number>();
 docs.forEach(d=>{const r=d.slug.split('/')[0];docsByProject.set(r,(docsByProject.get(r)??0)+1)});
 const base=locale==='en'?'/en':'/ko'; const c=locale==='en'?{
 title:'Open source work, with the reasoning included.',desc:'A portfolio of reusable answers to recurring platform problems — built, verified, operated, and improved in public.',storyTitle:'Start with the story.',storyDesc:'Why these projects exist, how they connect to Narwhal, what OpenForge standardizes, and why their licenses make adoption reviewable.',story:'Open OSS Story →',projects:'Browse projects',projectDesc:'Explore the individual boundaries after the overall system makes sense.',problem:'Problem',approach:'Approach',view:'View project →',docs:'docs',standard:'Documentation is part of the product',standardDesc:'Each project explains its problem, architecture, operation, verification, current state, and relationship to the wider OSS system.'
 }:{title:'오픈소스에 결과만이 아니라, 만든 이유까지 남깁니다.',desc:'반복되는 플랫폼 문제를 재사용 가능한 OSS로 분리하고, 실제 운영으로 검증하고, 다시 표준화한 engineering portfolio입니다.',storyTitle:'먼저 Story부터 보세요.',storyDesc:'왜 만들었는지, Narwhal과 어떻게 연결되는지, OpenForge가 어떤 insight를 표준화하는지, 라이선스와 활용성까지 한 번에 설명합니다.',story:'OSS Story 보기 →',projects:'프로젝트 탐색',projectDesc:'전체 맥락을 이해한 뒤 각각의 OSS 경계와 문서를 살펴볼 수 있습니다.',problem:'Problem',approach:'Approach',view:'프로젝트 보기 →',docs:'docs',standard:'문서도 제품의 일부입니다',standardDesc:'각 프로젝트의 문제, 아키텍처, 운영, 검증, 현재 상태와 전체 포트폴리오와의 관계를 함께 설명합니다.'};
 return <div className="mx-auto max-w-[1240px] px-5 py-10 sm:px-7 lg:py-16" style={{color:'var(--text)'}}>
  <section className="relative overflow-hidden rounded-[32px] border p-7 sm:p-11 lg:p-14" style={{borderColor:'var(--border)',backgroundColor:'var(--surface)'}}><div className="absolute -right-16 -top-20 h-64 w-64 rounded-full border" style={{borderColor:'var(--border-hi)'}}/><div className="absolute right-14 top-10 h-32 w-32 rounded-full border" style={{borderColor:'var(--accent)',opacity:.18}}/><div className="relative max-w-4xl"><div className="text-[10px] font-bold uppercase tracking-[.22em]" style={{color:'var(--accent)'}}>OSS WORKBENCH</div><h1 className="mt-5 text-4xl font-semibold tracking-[-.05em] sm:text-6xl lg:text-7xl">{c.title}</h1><p className="mt-6 max-w-3xl text-base leading-8 sm:text-lg" style={{color:'var(--text-muted)'}}>{c.desc}</p></div></section>
  <Link href={`${base}/oss/story/`} className="group mt-5 block rounded-[28px] border p-7 transition-transform duration-200 hover:-translate-y-1 sm:p-9" style={{borderColor:'var(--accent)',background:'linear-gradient(135deg,color-mix(in srgb,var(--accent-dim) 85%,var(--surface)),var(--surface))'}}><div className="grid gap-6 lg:grid-cols-[1fr_auto] lg:items-end"><div><div className="text-[10px] font-bold uppercase tracking-[.22em]" style={{color:'var(--accent)'}}>01 / STORY</div><h2 className="mt-3 text-3xl font-semibold tracking-[-.04em] sm:text-4xl">{c.storyTitle}</h2><p className="mt-4 max-w-3xl text-sm leading-7 sm:text-base" style={{color:'var(--text-muted)'}}>{c.storyDesc}</p></div><span className="inline-flex shrink-0 items-center rounded-full px-5 py-3 text-sm font-semibold" style={{backgroundColor:'var(--accent)',color:'var(--accent-fg)'}}>{c.story}</span></div></Link>
  <section className="mt-16"><div className="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><div className="text-[10px] font-bold uppercase tracking-[.22em]" style={{color:'var(--accent)'}}>02 / PORTFOLIO</div><h2 className="mt-2 text-3xl font-semibold tracking-[-.04em]">{c.projects}</h2></div><p className="max-w-xl text-sm leading-6 sm:text-right" style={{color:'var(--text-muted)'}}>{c.projectDesc}</p></div>
   <div className="mt-7 grid gap-3 md:grid-cols-4">{[['OpenForge','Standards'],['Small OSS','Focused capability'],['Narwhal','Integration'],['Feedback','Lessons → standards']].map(([a,b],i)=><div key={a} className="rounded-2xl border p-5" style={{borderColor:'var(--border)',backgroundColor:'var(--surface)'}}><div className="font-mono text-[10px]" style={{color:'var(--accent)'}}>0{i+1}</div><div className="mt-5 font-semibold">{a}</div><div className="mt-1 text-xs" style={{color:'var(--text-muted)'}}>{b}</div></div>)}</div>
   <div className="mt-10 space-y-12">{groups.map(group=><section key={group.label}><div className="max-w-3xl"><div className="text-[10px] font-bold uppercase tracking-[.18em]" style={{color:'var(--accent)'}}>{group.label}</div><p className="mt-2 text-sm leading-6" style={{color:'var(--text-muted)'}}>{group.description}</p></div><div className="mt-5 grid gap-4 md:grid-cols-2">{group.projects.map(slug=>{const p=bySlug.get(slug);if(!p)return null;const count=docsByProject.get(slug)??0;return <Link key={slug} href={`${base}/oss/${slug}/`} className="group rounded-[22px] border p-6 transition-transform duration-200 hover:-translate-y-1" style={{borderColor:'var(--border)',backgroundColor:'var(--surface)'}}><div className="flex items-start justify-between gap-4"><div><div className="text-[10px] font-bold uppercase tracking-[.16em]" style={{color:'var(--text-faint)'}}>Open Source Project</div><h3 className="mt-2 text-2xl font-semibold">{p.title}</h3></div><div className="rounded-full border px-3 py-1 text-[10px]" style={{borderColor:'var(--border)',color:'var(--text-faint)'}}>{count} {c.docs}</div></div><p className="mt-4 text-sm leading-6" style={{color:'var(--text-muted)'}}>{p.description}</p>{p.problem&&<div className="mt-5 rounded-xl p-4" style={{backgroundColor:'var(--surface-hi)'}}><div className="text-[10px] font-bold uppercase tracking-[.14em]" style={{color:'var(--text-faint)'}}>{c.problem}</div><p className="mt-2 text-sm leading-6" style={{color:'var(--text-muted)'}}>{p.problem}</p></div>}{p.solution&&<div className="mt-3 rounded-xl p-4" style={{backgroundColor:'var(--surface-hi)'}}><div className="text-[10px] font-bold uppercase tracking-[.14em]" style={{color:'var(--text-faint)'}}>{c.approach}</div><p className="mt-2 text-sm leading-6" style={{color:'var(--text-muted)'}}>{p.solution}</p></div>}<div className="mt-5 text-sm font-semibold" style={{color:'var(--accent)'}}>{c.view}</div></Link>})}</div></section>)}</div></section>
  <Link href={`${base}/oss/story/`} className="mt-14 flex flex-col gap-2 rounded-2xl border p-6 sm:flex-row sm:items-center sm:justify-between" style={{borderColor:'var(--border)',backgroundColor:'var(--surface)'}}><div><div className="text-[10px] font-bold uppercase tracking-[.18em]" style={{color:'var(--accent)'}}>03 / CONTEXT</div><div className="mt-2 text-lg font-semibold">{c.storyTitle}</div></div><span className="text-sm font-semibold" style={{color:'var(--accent)'}}>{c.story}</span></Link>
  <section className="mt-16 border-t pt-10" style={{borderColor:'var(--border)'}}><h2 className="text-2xl font-semibold">{c.standard}</h2><p className="mt-3 max-w-4xl text-sm leading-7" style={{color:'var(--text-muted)'}}>{c.standardDesc}</p></section>
 </div>;
}
