type Positioning = { role:string; statementKo:string; statementEn:string; evidence:string[] };

const POSITIONING: Record<string, Positioning> = {
  narwhal: { role:'Flagship Platform', statementKo:'복잡한 Kubernetes 플랫폼의 설치보다 integration seam을 재현·검증·운영 가능한 engineering system으로 만드는 프로젝트입니다.', statementEn:'A Kubernetes platform engineering system focused on reproducible, verifiable, operable integration seams rather than installation alone.', evidence:['Platform integration','Verification-driven','GitOps & operations'] },
  'narwhal-portal': { role:'Platform Experience Layer', statementKo:'Narwhal의 GitOps, SSO, observability, security, cost, governance 신호를 하나의 developer/operator workbench로 묶는 day-0~day-2 경험 계층입니다.', statementEn:'The day-0 to day-2 experience layer that brings Narwhal GitOps, SSO, observability, security, cost and governance signals into one developer/operator workbench.', evidence:['Operational surface','Authoritative-source integration','Developer & operator UX'] },
  'nfs-quota-agent': { role:'Reusable Component', statementKo:'Narwhal에 종속되지 않고 Kubernetes shared storage 환경에서 독립 설치·검증·재사용할 수 있는 filesystem quota component를 지향합니다.', statementEn:'An independently installable and verifiable filesystem quota component for Kubernetes shared-storage environments, with a lifecycle separate from Narwhal.', evidence:['Shared NFS quota','Filesystem enforcement','Independent lifecycle'] },
  kubemetal: { role:'Emerging / Cloud-native AI', statementKo:'Apple Silicon의 native ML compute와 Kubernetes control plane을 연결해 local AI infrastructure의 실용적인 경계를 검증합니다.', statementEn:'Explores the practical boundary of local AI infrastructure by connecting Apple Silicon native ML compute with a Kubernetes control plane.', evidence:['Apple Silicon','Kubernetes control plane','Native ML compute'] },
  openforge: { role:'Engineering Foundation', statementKo:'각 OSS가 같은 저장소 모양만 갖추는 것이 아니라 documentation, CI/CD, security, release, governance 원칙을 반복 적용하도록 만드는 공통 engineering blueprint입니다.', statementEn:'A shared engineering blueprint for repeatedly applying documentation, CI/CD, security, release and governance practices instead of merely standardizing repository shape.', evidence:['OSS standards','Supply chain','Governance & docs'] },
  clusterdeck: { role:'Workstation Access Layer', statementKo:'자주 재생성되는 VM·Kubernetes 환경을 IP가 아닌 안정적인 Profile로 다루고 SSH, Bastion/ProxyJump, kubeconfig 연결을 로컬 워크스테이션에서 자동화합니다.', statementEn:'Treats frequently recreated VM and Kubernetes environments as stable Profiles rather than IP addresses, automating SSH, Bastion/ProxyJump and kubeconfig access from the workstation.', evidence:['Profile-oriented access','SSH & ProxyJump','kubeconfig normalization'] },
  ldapium: { role:'Identity Infrastructure', statementKo:'새 LDAP 구현이 아니라 upstream OpenLDAP을 Kubernetes 환경에서 안전하고 반복 가능하게 빌드·패키징·배포·운영하는 identity infrastructure boundary를 제공합니다.', statementEn:'Provides an identity-infrastructure boundary for safely and repeatably building, packaging, deploying and operating upstream OpenLDAP in Kubernetes environments.', evidence:['Upstream packaging','Zero-default-password','Helm & air-gap'] },
  'kube-ready-box': { role:'Node Foundation', statementKo:'Kubernetes 설치기 대신, ARM64/AMD64와 여러 provider에서 반복 사용할 수 있는 OS readiness baseline을 Packer와 Vagrant image로 제공합니다.', statementEn:'Provides a reusable OS-readiness baseline through Packer and Vagrant images across ARM64/AMD64 and multiple providers instead of bundling a Kubernetes installer.', evidence:['OS readiness','Multi-arch','Filesystem variants'] },
  beluga: { role:'Data Platform Reference', statementKo:'Kafka·CDC·Flink·Iceberg·Trino·Superset·Airflow의 데이터 lifecycle을 로컬 Kubernetes에서 end-to-end로 연결하고 검증하는 reference platform입니다.', statementEn:'A reference data platform that connects and verifies the Kafka/CDC, Flink, Iceberg, Trino, Superset and Airflow lifecycle end to end on local Kubernetes.', evidence:['CDC & streaming','Lakehouse lifecycle','E2E validation'] },
  'beluga-manager': { role:'Data Control Plane', statementKo:'개별 OSS UI를 복제하지 않고 authoritative API를 adapter로 연결해 Pipeline, Data Asset, Service, Operations 관점의 cross-system context를 제공합니다.', statementEn:'A cross-system data control plane that connects authoritative OSS APIs through adapters instead of reimplementing each product UI.', evidence:['Unified domain API','Correlation layer','Read-first control plane'] },
};

export function OssProjectPositioning({ slug, locale='ko' }: { slug:string; locale?:'ko'|'en' }) {
  const item=POSITIONING[slug];
  if (!item) return null;
  const statement=locale==='en'?item.statementEn:item.statementKo;
  return <section className="mb-10 overflow-hidden rounded-2xl" style={{ border:'1px solid var(--border)', backgroundColor:'var(--bg-subtle)' }}><div className="grid gap-0 lg:grid-cols-[0.85fr_2fr]"><div className="p-6 sm:p-7 lg:border-r" style={{ borderColor:'var(--border)' }}><div className="font-mono text-[10px] font-bold uppercase tracking-[0.16em]" style={{ color:'var(--accent)' }}>ECOSYSTEM ROLE</div><div className="mt-3 text-2xl font-semibold tracking-tight">{item.role}</div></div><div className="p-6 sm:p-7"><p className="text-[15px] leading-7" style={{ color:'var(--text-muted)' }}>{statement}</p><div className="mt-5 flex flex-wrap gap-2">{item.evidence.map((label)=><span key={label} className="rounded-full px-3 py-1.5 text-[11px] font-medium" style={{ border:'1px solid var(--border)', backgroundColor:'var(--surface)', color:'var(--text-faint)' }}>{label}</span>)}</div></div></div></section>;
}
