'use client';

import Link from 'next/link';
import { useEffect, useRef, useState } from 'react';

type Locale = 'ko' | 'en';
const slideCount = 8;
const stats = [
  ['82%', 'Kubernetes production usage', 'CNCF Annual Cloud Native Survey · 2026'],
  ['66%', 'Generative AI inference on Kubernetes', 'CNCF Annual Cloud Native Survey · 2026'],
  ['~1B', 'Open-source / public contributions in 2024', 'GitHub Octoverse · 2024'],
] as const;
const repos = [
  ['OpenForge','Standards','repo rules · governance','openforge'],
  ['kube-ready-box','Baseline','reproducible node foundation','kube-ready-box'],
  ['Narwhal','Integration','Kubernetes IDP','narwhal'],
  ['Narwhal Portal','Experience','developer / operator experience','narwhal-portal'],
  ['nfs-quota-agent','Storage','quota enforcement','nfs-quota-agent'],
  ['ldapium','Identity','directory boundary','ldapium'],
  ['Beluga','Data','CDC → lakehouse → query','beluga'],
  ['KubeMetal','AI / Edge','Apple Silicon local AI','kubemetal'],
] as const;

export default function OssStoryInfographic({ locale }: { locale: Locale }) {
  const en = locale === 'en';
  const base = en ? '/en' : '/ko';
  const scroller = useRef<HTMLDivElement>(null);
  const [active, setActive] = useState(0);

  const go = (index: number) => {
    const root = scroller.current;
    if (!root) return;
    const next = Math.max(0, Math.min(slideCount - 1, index));
    root.scrollTo({ left: next * root.clientWidth, behavior: 'smooth' });
    setActive(next);
  };

  useEffect(() => {
    const root = scroller.current;
    if (!root) return;
    const slides = [...root.querySelectorAll<HTMLElement>('[data-slide]')];
    const observer = new IntersectionObserver(entries => {
      const best = entries.filter(e => e.isIntersecting).sort((a,b) => b.intersectionRatio - a.intersectionRatio)[0];
      if (best) setActive(Number((best.target as HTMLElement).dataset.index));
    }, { root, threshold: [.5, .75] });
    slides.forEach(s => observer.observe(s));
    const key = (e: KeyboardEvent) => {
      if (e.key === 'ArrowRight') { e.preventDefault(); go(active + 1); }
      if (e.key === 'ArrowLeft') { e.preventDefault(); go(active - 1); }
      if (e.key === 'Home') { e.preventDefault(); go(0); }
      if (e.key === 'End') { e.preventDefault(); go(slideCount - 1); }
    };
    window.addEventListener('keydown', key);
    return () => { observer.disconnect(); window.removeEventListener('keydown', key); };
  }, [active]);

  const ko = {
    heroTitle:'OSS는 저장소가 아니라 시스템입니다.', heroLead:'코드를 공개하는 것보다 중요한 것은 문제 정의, 재현 가능한 기반, 통합, 검증, 문서화가 하나의 흐름으로 연결되는 것입니다.',
    signalTitle:'왜 지금 OSS Engineering인가', signalLead:'Cloud Native와 AI가 보편화될수록 개별 기술보다 통합과 운영의 복잡성을 설명할 수 있는 evidence가 중요해집니다.',
    complexityTitle:'복잡성은 기술 수가 아니라 경계에서 생깁니다.', complexityLead:'Identity, Network, Storage, Delivery처럼 시스템 사이의 seam이 실제 장애와 운영 비용을 만듭니다.',
    governanceTitle:'좋은 OSS는 코드와 운영 규칙을 함께 설계합니다.', governanceLead:'라이선스와 배포 방식, dependency boundary, 문서와 release 규칙을 초기에 정리하면 프로젝트가 커져도 방향을 잃지 않습니다.',
    loopTitle:'Build → Verify → Learn → Share', loopLead:'기능 개발을 끝으로 보지 않고, 통합·검증·문서·회고까지 하나의 engineering loop로 관리합니다.',
    archTitle:'프로젝트는 역할별로 연결됩니다.', archLead:'표준과 기반을 만들고, 플랫폼을 통합하고, 필요한 기능을 독립 OSS로 분리하며 다시 전체 시스템에 연결합니다.',
    evidenceTitle:'결과보다 검증 가능한 신호를 남깁니다.', evidenceLead:'앱 수, regression check, incident lesson처럼 다시 확인할 수 있는 evidence가 프로젝트의 신뢰도를 만듭니다.',
    mapTitle:'하나의 포트폴리오가 아니라 하나의 Workbench', mapLead:'각 저장소는 독립 프로젝트이면서도 Standards → Baseline → Platform → Capability → Evidence 흐름 안에서 서로 연결됩니다.'
  };
  const tx = en ? {
    heroTitle:'Open source is a system, not a repository.', heroLead:'Publishing code matters less than connecting problem definition, reproducible foundations, integration, verification, and documentation into one engineering flow.',
    signalTitle:'Why OSS engineering now', signalLead:'As Cloud Native and AI become mainstream, evidence of integration and operations matters more than a long list of technologies.',
    complexityTitle:'Complexity appears at boundaries.', complexityLead:'Identity, network, storage, and delivery seams are where operational cost and failure actually emerge.',
    governanceTitle:'Good OSS designs code and operating rules together.', governanceLead:'License, distribution, dependency boundaries, documentation, and release rules keep a growing project coherent.',
    loopTitle:'Build → Verify → Learn → Share', loopLead:'Development is not done at feature completion. Integration, verification, documentation, and lessons are one engineering loop.',
    archTitle:'Projects connect by role.', archLead:'Standards create the rules, baselines make environments repeatable, platforms integrate them, and focused OSS fills capability gaps.',
    evidenceTitle:'Leave verifiable signals, not claims.', evidenceLead:'App counts, regression checks, and incident lessons are evidence that can be inspected again.',
    mapTitle:'Not a portfolio. A workbench.', mapLead:'Each repository stands alone, but together they form a Standards → Baseline → Platform → Capability → Evidence system.'
  } : ko;

  return <main className="oss-horizontal oss-infographic">
    <style>{`
      .oss-infographic{min-height:calc(100svh - 64px);position:relative;overflow:hidden;background:var(--bg);color:var(--text)}
      .oss-infographic *{box-sizing:border-box}.deck-progress{position:absolute;z-index:50;left:0;top:0;height:3px;background:var(--accent);transition:width .35s ease}.deck-top{position:absolute;z-index:45;left:18px;right:18px;top:14px;display:flex;justify-content:space-between;pointer-events:none}.deck-mark{font:800 9px ui-monospace,SFMono-Regular,Menlo,monospace;letter-spacing:.16em;color:var(--text-faint)}
      .deck-scroll{height:calc(100svh - 64px);display:flex;overflow-x:auto;overflow-y:hidden;scroll-snap-type:x mandatory;scrollbar-width:none;-webkit-overflow-scrolling:touch}.deck-scroll::-webkit-scrollbar{display:none}.deck-slide{position:relative;flex:0 0 100%;min-width:100%;height:100%;scroll-snap-align:start;padding:68px clamp(20px,5vw,76px) 58px;display:flex;align-items:center;overflow:hidden}.deck-slide:before{content:"";position:absolute;inset:0;background:radial-gradient(circle at 82% 18%,color-mix(in srgb,var(--accent) 12%,transparent),transparent 34%);pointer-events:none}.slide-inner{width:min(1260px,100%);margin:auto;position:relative;z-index:2}.eyebrow{font:800 10px ui-monospace,SFMono-Regular,Menlo,monospace;letter-spacing:.18em;color:var(--accent)}.slide-title{margin-top:13px;max-width:1080px;font-size:clamp(42px,5.6vw,82px);line-height:.96;letter-spacing:-.055em}.slide-lead{margin-top:18px;max-width:900px;color:var(--text-muted);font-size:clamp(16px,1.5vw,21px);line-height:1.58}.slide-no{position:absolute;right:18px;top:56px;color:var(--text-faint);font:800 9px ui-monospace,SFMono-Regular,Menlo,monospace}.visual{margin-top:28px}.card{border:1px solid var(--border);background:var(--surface);border-radius:20px;padding:18px}.muted{color:var(--text-muted)}.mono{font:800 9px ui-monospace,SFMono-Regular,Menlo,monospace;letter-spacing:.1em;color:var(--text-faint)}
      .hero-grid{display:grid;grid-template-columns:1fr 1fr;gap:26px;align-items:center}.system-map{position:relative;min-height:410px;border:1px solid var(--border);border-radius:28px;background:linear-gradient(145deg,var(--surface),var(--surface-hi));padding:28px;display:grid;place-items:center;overflow:hidden}.hub{width:148px;height:148px;border-radius:34px;background:var(--accent);color:var(--accent-fg);display:grid;place-items:center;text-align:center;font-weight:900;line-height:1.1;box-shadow:0 20px 50px color-mix(in srgb,var(--accent) 22%,transparent)}.orbit{position:absolute;border:1px dashed color-mix(in srgb,var(--accent) 40%,var(--border));border-radius:999px}.o1{inset:12%}.o2{inset:26%}.node{position:absolute;padding:10px 12px;border-radius:14px;border:1px solid var(--border);background:var(--surface);font-size:11px;font-weight:800;box-shadow:0 8px 22px rgba(0,0,0,.06)}.n1{top:9%;left:8%}.n2{top:12%;right:8%}.n3{bottom:13%;right:7%}.n4{bottom:10%;left:9%}.flowline{display:grid;grid-template-columns:repeat(5,1fr);gap:8px}.flowstep{position:relative;border:1px solid var(--border);background:var(--surface);border-radius:16px;padding:16px;min-height:108px}.flowstep b{display:block;margin-top:11px;font-size:15px}.flowstep span{font-size:10px;color:var(--text-muted)}.flowstep:not(:last-child):after{content:'→';position:absolute;right:-9px;top:45%;color:var(--accent);font-weight:900;z-index:2}
      .signal-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.signal{border:1px solid var(--border);border-radius:22px;background:var(--surface);padding:20px;min-height:230px}.donut{--p:50;position:relative;width:112px;height:112px;border-radius:50%;background:conic-gradient(var(--accent) calc(var(--p)*1%),var(--border) 0);display:grid;place-items:center}.donut:after{content:"";position:absolute;inset:13px;border-radius:50%;background:var(--surface)}.donut strong{position:relative;z-index:1;font-size:24px}.signal h3{margin-top:16px;font-size:15px}.signal p{margin-top:7px;font-size:11px;line-height:1.5;color:var(--text-muted)}.signal small{display:block;margin-top:12px;color:var(--text-faint);font-size:9px}
      .seam-map{display:grid;grid-template-columns:1.1fr .9fr;gap:16px}.layer-stack{display:grid;gap:8px}.layer{display:grid;grid-template-columns:120px 1fr auto;gap:14px;align-items:center;border:1px solid var(--border);background:var(--surface);border-radius:15px;padding:14px}.layer b{font-size:13px}.layer span{font-size:10px;color:var(--text-muted)}.heat{width:12px;height:12px;border-radius:50%;background:var(--signal);box-shadow:0 0 0 5px color-mix(in srgb,var(--signal) 14%,transparent)}.seam-grid{display:grid;grid-template-columns:1fr 1fr;gap:9px}.seam{border:1px solid var(--border);border-radius:17px;background:var(--surface-hi);padding:15px;min-height:118px}.seam b{font-size:10px;color:var(--accent)}.seam strong{display:block;margin-top:16px;font-size:15px}.seam span{display:block;margin-top:6px;font-size:10px;color:var(--text-muted)}
      .matrix{display:grid;grid-template-columns:140px repeat(4,1fr);gap:6px}.matrix>*{border:1px solid var(--border);border-radius:13px;padding:12px;background:var(--surface);font-size:10px}.matrix .head{font-weight:900;color:var(--accent);background:var(--surface-hi)}.matrix .rowhead{font-weight:900}.dot-ok{display:inline-block;width:9px;height:9px;border-radius:50%;background:var(--accent);margin-right:6px}.dot-warn{display:inline-block;width:9px;height:9px;border-radius:50%;background:var(--signal);margin-right:6px}
      .loop{display:grid;grid-template-columns:repeat(6,1fr);gap:8px}.loop-card{position:relative;border:1px solid var(--border);border-radius:18px;background:var(--surface);padding:16px;min-height:164px}.loop-card b{font:800 9px ui-monospace,SFMono-Regular,Menlo,monospace;color:var(--accent)}.loop-card strong{display:block;margin-top:20px;font-size:16px}.loop-card p{margin-top:7px;font-size:10px;line-height:1.5;color:var(--text-muted)}.loop-card:not(:last-child):after{content:'→';position:absolute;right:-8px;top:46%;z-index:2;color:var(--accent);font-weight:900}.loop-card:last-child{background:var(--accent-dim)}
      .arch{display:grid;grid-template-columns:1fr 1.2fr 1fr;gap:12px;align-items:stretch}.arch-col{display:grid;gap:10px}.arch-box{border:1px solid var(--border);border-radius:17px;background:var(--surface);padding:16px}.arch-box.core{border-color:color-mix(in srgb,var(--accent) 55%,var(--border));background:var(--accent-dim)}.arch-box b{display:block;font-size:12px;color:var(--accent)}.arch-box strong{display:block;margin-top:8px;font-size:17px}.arch-box span{display:block;margin-top:5px;font-size:10px;color:var(--text-muted)}.arch-arrow{display:grid;place-items:center;color:var(--accent);font-size:24px}
      .evidence-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.evidence-card{border:1px solid var(--border);border-radius:22px;background:var(--surface);padding:20px}.evidence-num{font-size:clamp(48px,5vw,72px);font-weight:900;line-height:.9;letter-spacing:-.06em;color:var(--accent)}.evidence-card strong{display:block;margin-top:14px}.evidence-card p{margin-top:8px;font-size:11px;line-height:1.5;color:var(--text-muted)}.bar{margin-top:18px;height:7px;border-radius:99px;background:var(--border);overflow:hidden}.bar i{display:block;height:100%;border-radius:99px;background:var(--accent)}
      .repo-map{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.repo{border:1px solid var(--border);background:var(--surface);border-radius:18px;padding:15px;text-decoration:none;color:inherit;min-height:130px;display:flex;flex-direction:column}.repo:hover{border-color:var(--accent);transform:translateY(-2px)}.repo small{font:800 9px ui-monospace,SFMono-Regular,Menlo,monospace;color:var(--accent)}.repo strong{margin-top:9px;font-size:16px}.repo p{margin-top:6px;font-size:10px;line-height:1.45;color:var(--text-muted)}.repo em{margin-top:auto;padding-top:10px;font-style:normal;font-size:10px;font-weight:800;color:var(--accent)}
      .deck-nav{position:absolute;z-index:45;left:12px;right:12px;top:50%;transform:translateY(-50%);display:flex;justify-content:space-between;pointer-events:none}.deck-nav button{pointer-events:auto;width:42px;height:42px;border:1px solid var(--border);border-radius:50%;background:color-mix(in srgb,var(--surface) 90%,transparent);backdrop-filter:blur(10px);cursor:pointer}.deck-nav button:disabled{opacity:.28}.deck-dots{position:absolute;z-index:45;left:50%;bottom:16px;transform:translateX(-50%);display:flex;gap:6px}.deck-dots button{height:6px;border:0;border-radius:99px;background:var(--border-strong);padding:0;transition:width .25s,background .25s;cursor:pointer}
      @media(max-width:900px){.hero-grid,.seam-map{grid-template-columns:1fr}.signal-grid,.evidence-grid{grid-template-columns:1fr 1fr}.repo-map{grid-template-columns:1fr 1fr}.loop{grid-template-columns:1fr 1fr 1fr}.arch{grid-template-columns:1fr}.arch-arrow{transform:rotate(90deg)}.system-map{min-height:300px}.slide-title{font-size:clamp(38px,8vw,64px)}}
      @media(max-width:620px){.deck-scroll{height:calc(100svh - 64px);overflow-x:hidden;overflow-y:hidden;scroll-snap-type:none;touch-action:pan-y}.deck-slide{height:100%;min-height:calc(100svh - 64px);overflow-y:auto;padding:46px 14px 34px}.slide-inner{padding-bottom:18px}.slide-title{font-size:clamp(32px,10vw,50px);line-height:.98}.slide-lead{font-size:14px;line-height:1.52;margin-top:13px}.visual{margin-top:18px}.hero-grid{gap:14px}.system-map{min-height:240px;border-radius:20px}.hub{width:108px;height:108px;border-radius:24px;font-size:13px}.node{font-size:9px;padding:8px}.flowline{grid-template-columns:1fr}.flowstep{min-height:0;padding:12px}.flowstep:not(:last-child):after{content:'↓';right:auto;left:50%;top:auto;bottom:-12px}.signal-grid,.evidence-grid,.repo-map{grid-template-columns:1fr}.signal{min-height:0;padding:15px}.donut{width:86px;height:86px}.seam-grid{grid-template-columns:1fr}.layer{grid-template-columns:88px 1fr auto;padding:11px}.matrix{grid-template-columns:100px repeat(4,112px);overflow-x:auto;padding-bottom:8px}.loop{grid-template-columns:1fr}.loop-card{min-height:0}.loop-card:not(:last-child):after{content:'↓';right:auto;left:50%;top:auto;bottom:-12px}.repo-map{gap:8px}.repo{min-height:0}.deck-nav{display:none}.deck-dots{bottom:8px}.slide-no{top:38px;right:12px}}
      @media(prefers-reduced-motion:reduce){.oss-infographic *{scroll-behavior:auto!important;transition:none!important}}
    `}</style>
    <div className="deck-progress" style={{ width: `${((active+1)/slideCount)*100}%` }} />
    <div className="deck-top"><span className="deck-mark">OSS STORY / INFOGRAPHIC DECK</span><span className="deck-mark">{String(active+1).padStart(2,'0')} / {String(slideCount).padStart(2,'0')}</span></div>
    <div ref={scroller} className="deck-scroll">
      <section className="deck-slide" data-slide data-index="0"><span className="slide-no">01 / 08</span><div className="slide-inner"><div className="hero-grid"><div><div className="eyebrow">OPEN SOURCE ENGINEERING</div><h1 className="slide-title">{tx.heroTitle}</h1><p className="slide-lead">{tx.heroLead}</p><div className="visual flowline">{[['01','Problem'],['02','Standards'],['03','Build'],['04','Verify'],['05','Share']].map(([n,t])=><div className="flowstep" key={t}><span>{n}</span><b>{t}</b></div>)}</div></div><div className="system-map"><div className="orbit o1"/><div className="orbit o2"/><div className="hub">OSS<br/>WORKBENCH</div><div className="node n1">Standards</div><div className="node n2">Platform</div><div className="node n3">Evidence</div><div className="node n4">Learning</div></div></div></div></section>
      <section className="deck-slide" data-slide data-index="1"><span className="slide-no">02 / 08</span><div className="slide-inner"><div className="eyebrow">SIGNALS</div><h2 className="slide-title">{tx.signalTitle}</h2><p className="slide-lead">{tx.signalLead}</p><div className="visual signal-grid">{stats.map(([num,label,source],i)=><div className="signal" key={label}><div className="donut" style={{'--p': i===0?82:i===1?66:92} as React.CSSProperties}><strong>{num}</strong></div><h3>{en?label:[ 'Kubernetes production 사용','생성형 AI inference의 Kubernetes 활용','2024 OSS/public 기여 규모'][i]}</h3><p>{en?'The signal is less about a single tool and more about operational integration becoming mainstream.':'단일 기술 채택보다 운영·통합 역량이 점점 더 중요해지는 흐름을 보여줍니다.'}</p><small>{source}</small></div>)}</div></div></section>
      <section className="deck-slide" data-slide data-index="2"><span className="slide-no">03 / 08</span><div className="slide-inner"><div className="eyebrow">COMPLEXITY MAP</div><h2 className="slide-title">{tx.complexityTitle}</h2><p className="slide-lead">{tx.complexityLead}</p><div className="visual seam-map"><div className="layer-stack">{[['Experience','Portal / API / CLI'],['Delivery','GitOps / CI / Release'],['Platform','Kubernetes / Service Mesh'],['Foundation','Node / Network / Storage']].map(([a,b])=><div className="layer" key={a}><b>{a}</b><span>{b}</span><i className="heat"/></div>)}</div><div className="seam-grid">{[['IDENTITY','SSO ↔ RBAC','Who can do what?'],['NETWORK','Ingress ↔ Mesh','Where does traffic flow?'],['STORAGE','PVC ↔ Backend','Who owns capacity?'],['DELIVERY','Git ↔ Runtime','What is the source of truth?']].map(([a,b,c])=><div className="seam" key={a}><b>{a}</b><strong>{b}</strong><span>{c}</span></div>)}</div></div></div></section>
      <section className="deck-slide" data-slide data-index="3"><span className="slide-no">04 / 08</span><div className="slide-inner"><div className="eyebrow">GOVERNANCE</div><h2 className="slide-title">{tx.governanceTitle}</h2><p className="slide-lead">{tx.governanceLead}</p><div className="visual matrix"><div className="head">AREA</div><div className="head">Source</div><div className="head">Dependency</div><div className="head">Distribution</div><div className="head">Docs</div>{[['License','clear','check','notice','state'],['Release','tag','pin','artifact','notes'],['Security','review','scan','verify','record'],['Governance','rules','policy','ownership','guide']].flatMap(([r,...cells])=>[<div className="rowhead" key={`${r}-h`}>{r}</div>,...cells.map((c,i)=><div key={`${r}-${i}`}><span className={i===2?'dot-warn':'dot-ok'}/>{c}</div>)])}</div></div></section>
      <section className="deck-slide" data-slide data-index="4"><span className="slide-no">05 / 08</span><div className="slide-inner"><div className="eyebrow">ENGINEERING LOOP</div><h2 className="slide-title">{tx.loopTitle}</h2><p className="slide-lead">{tx.loopLead}</p><div className="visual loop">{[['01','Define','problem / constraint'],['02','Build','small working slice'],['03','Integrate','connect boundaries'],['04','Verify','tests / checks'],['05','Document','decision / evidence'],['06','Share','release / lesson']].map(([n,t,d])=><div className="loop-card" key={n}><b>{n}</b><strong>{t}</strong><p>{d}</p></div>)}</div></div></section>
      <section className="deck-slide" data-slide data-index="5"><span className="slide-no">06 / 08</span><div className="slide-inner"><div className="eyebrow">SYSTEM ARCHITECTURE</div><h2 className="slide-title">{tx.archTitle}</h2><p className="slide-lead">{tx.archLead}</p><div className="visual arch"><div className="arch-col"><div className="arch-box"><b>STANDARDS</b><strong>OpenForge</strong><span>rules · templates · governance</span></div><div className="arch-box"><b>BASELINE</b><strong>kube-ready-box</strong><span>repeatable node foundation</span></div></div><div className="arch-arrow">→</div><div className="arch-col"><div className="arch-box core"><b>PLATFORM</b><strong>Narwhal</strong><span>IDP · GitOps · SSO · observability</span></div><div className="arch-box core"><b>EXPERIENCE</b><strong>Narwhal Portal</strong><span>developer / operator surface</span></div></div><div className="arch-arrow">→</div><div className="arch-col"><div className="arch-box"><b>CAPABILITIES</b><strong>ldapium · nfs-quota-agent</strong><span>identity · storage boundaries</span></div><div className="arch-box"><b>WORKLOADS</b><strong>Beluga · KubeMetal</strong><span>data · AI / edge</span></div></div></div></section>
      <section className="deck-slide" data-slide data-index="6"><span className="slide-no">07 / 08</span><div className="slide-inner"><div className="eyebrow">ENGINEERING EVIDENCE</div><h2 className="slide-title">{tx.evidenceTitle}</h2><p className="slide-lead">{tx.evidenceLead}</p><div className="visual evidence-grid"><div className="evidence-card"><div className="evidence-num">35</div><strong>Narwhal GitOps apps</strong><p>{en?'Integration breadth visible in the platform configuration.':'플랫폼 구성에서 확인 가능한 통합 범위.'}</p><div className="bar"><i style={{width:'82%'}}/></div></div><div className="evidence-card"><div className="evidence-num">51</div><strong>CI regression checks</strong><p>{en?'Repeatable checks reduce “works on my machine” confidence gaps.':'반복 가능한 검증으로 완료 여부를 객관화.'}</p><div className="bar"><i style={{width:'68%'}}/></div></div><div className="evidence-card"><div className="evidence-num">263</div><strong>integration / incident lessons</strong><p>{en?'Failures become reusable engineering knowledge.':'실패를 재사용 가능한 engineering knowledge로 전환.'}</p><div className="bar"><i style={{width:'94%'}}/></div></div></div></div></section>
      <section className="deck-slide" data-slide data-index="7"><span className="slide-no">08 / 08</span><div className="slide-inner"><div className="eyebrow">OSS WORKBENCH MAP</div><h2 className="slide-title">{tx.mapTitle}</h2><p className="slide-lead">{tx.mapLead}</p><div className="visual repo-map">{repos.map(([name,role,desc,slug])=><Link className="repo" key={name} href={`${base}/projects/${slug}`}><small>{role}</small><strong>{name}</strong><p>{desc}</p><em>OPEN →</em></Link>)}</div></div></section>
    </div>
    <div className="deck-nav"><button onClick={()=>go(active-1)} disabled={active===0} aria-label="Previous slide">←</button><button onClick={()=>go(active+1)} disabled={active===slideCount-1} aria-label="Next slide">→</button></div>
    <div className="deck-dots">{Array.from({length:slideCount}).map((_,i)=><button key={i} onClick={()=>go(i)} aria-label={`Slide ${i+1}`} style={{width:i===active?24:6,background:i===active?'var(--accent)':'var(--border-strong)'}}/>)}</div>
  </main>;
}
