'use client';

import Link from 'next/link';

const projects = [
  ['OpenForge', 'Engineering standards', '표준·템플릿·CI·보안·공급망·운영 insight를 재사용 가능한 기준으로 환원', 'https://github.com/dasomel/openforge'],
  ['kube-ready-box', 'Kubernetes baseline', '재현 가능한 Kubernetes 노드 베이스라인과 개발 환경을 제공', 'https://github.com/dasomel/kube-ready-box'],
  ['Narwhal', 'Internal Developer Platform', 'GitOps·IAM·Mesh·Observability·Storage·Backup·Policy를 하나의 운영 단위로 통합', 'https://github.com/dasomel/narwhal'],
  ['Narwhal Portal', 'Platform experience', '플랫폼 사용자가 클러스터와 서비스를 탐색하고 운영하는 관리 경험', 'https://github.com/dasomel/narwhal-portal'],
  ['nfs-quota-agent', 'Storage', 'NFS 기반 영속 스토리지의 quota 운영을 독립 컴포넌트로 보완', 'https://github.com/dasomel/nfs-quota-agent'],
  ['ldapium', 'Identity', 'LDAP/Directory 경계를 단순화하고 플랫폼 identity와 연결', 'https://github.com/dasomel/ldapium'],
  ['Beluga', 'Data platform', 'CDC부터 lakehouse·query까지 데이터 운영 흐름을 연결', 'https://github.com/dasomel/beluga'],
  ['KubeMetal', 'Local AI / Edge', 'Apple Silicon native compute와 Kubernetes control plane을 결합', 'https://github.com/dasomel/kubemetal'],
] as const;

function Footer({ no, text }: { no: string; text: string }) {
  return <div className="footer"><span>{text}</span><b>{no} / 08</b></div>;
}

function Stat({ value, title, detail, href }: { value: string; title: string; detail: string; href: string }) {
  return (
    <div className="stat">
      <div className="stat-value">{value}</div>
      <div className="stat-title">{title}</div>
      <p>{detail}</p>
      <a href={href} target="_blank" rel="noreferrer" className="stat-source">Source ↗</a>
    </div>
  );
}

function ProjectCard({ item, featured = false }: { item: (typeof projects)[number]; featured?: boolean }) {
  return (
    <a className={`project ${featured ? 'featured' : ''}`} href={item[3]} target="_blank" rel="noreferrer">
      <span className="project-role">{item[1]}</span>
      <strong>{item[0]}</strong>
      <span className="project-desc">{item[2]}</span>
      <span className="project-link">GitHub ↗</span>
    </a>
  );
}

export default function OssStoryPage() {
  return (
    <main className="story">
      <style>{`
        :root{--ink:#101214;--muted:#687078;--line:#dfe4e7;--paper:#f6f7f4;--card:#fff;--green:#08745c;--mint:#e5f4ef;--dark:#101415;--dark2:#171c1d}
        *{box-sizing:border-box}html{scroll-behavior:smooth;background:var(--paper)}body{margin:0;background:var(--paper);color:var(--ink);font-family:ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}
        .slide{width:min(100vw,1600px);min-height:100vh;aspect-ratio:16/9;margin:0 auto;padding:clamp(32px,5vw,84px);display:flex;flex-direction:column;justify-content:space-between;position:relative;overflow:hidden;background:var(--paper)}
        .slide.dark{background:var(--dark);color:#f3f6f5}.slide::before{content:"";position:absolute;inset:0;pointer-events:none;background:radial-gradient(circle at 100% 0,rgba(8,116,92,.09),transparent 34%)}.dark::before{background:radial-gradient(circle at 82% 12%,rgba(44,168,133,.18),transparent 30%)}
        .content,.footer{position:relative;z-index:1}.eyebrow{font-size:11px;font-weight:850;letter-spacing:.18em;text-transform:uppercase;color:var(--green)}.dark .eyebrow{color:#78d4b9}
        h1,h2,h3,p{margin:0}h1{font-size:clamp(48px,7vw,108px);line-height:.96;letter-spacing:-.055em;max-width:1150px}h2{font-size:clamp(35px,4.7vw,74px);line-height:1;letter-spacing:-.05em;max-width:1150px}h3{font-size:22px}.lead{margin-top:22px;max-width:950px;font-size:clamp(17px,1.55vw,25px);line-height:1.55;color:var(--muted)}.dark .lead{color:#c2c8cb}.footer{display:flex;justify-content:space-between;gap:20px;font-size:10px;color:#7a8288}.dark .footer{color:#7f898d}.footer b{letter-spacing:.09em}
        .hero{display:grid;grid-template-columns:1.1fr .9fr;gap:32px;align-items:center;height:100%}.orbit{width:min(90%,470px);aspect-ratio:1;border:2px solid var(--green);border-radius:50%;margin:auto;position:relative;background:linear-gradient(180deg,#edf9f4,#e4f2ed)}.core{position:absolute;left:50%;top:50%;transform:translate(-50%,-50%);background:var(--green);color:#fff;border-radius:18px;padding:24px 30px;font-size:24px;font-weight:900;box-shadow:0 15px 45px rgba(8,116,92,.22)}.orb{position:absolute;padding:8px 11px;border:1px solid rgba(8,116,92,.22);border-radius:999px;background:#fbfffd;font-size:12px;font-weight:850}.o1{top:5%;left:26%}.o2{top:29%;right:-3%}.o3{bottom:15%;right:8%}.o4{bottom:4%;left:22%}.o5{top:30%;left:-7%}
        .stats{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin-top:34px}.stat{border:1px solid var(--line);border-radius:24px;background:rgba(255,255,255,.8);padding:24px;min-height:230px;position:relative}.stat::after{content:"";position:absolute;left:0;right:0;bottom:0;height:5px;background:var(--green)}.stat-value{font-size:clamp(58px,6vw,94px);font-weight:900;letter-spacing:-.07em;line-height:.92;color:var(--green)}.stat-title{margin-top:12px;font-size:15px;font-weight:850}.stat p{margin-top:9px;font-size:12px;line-height:1.5;color:var(--muted)}.stat-source{display:inline-block;margin-top:18px;color:var(--green);font-size:10px;font-weight:800;text-decoration:none}
        .grid2{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-top:30px}.card{border:1px solid var(--line);background:#fff;border-radius:24px;padding:24px}.card strong{display:block;text-transform:uppercase;letter-spacing:.13em;font-size:11px;color:var(--green)}.card p{margin-top:10px;font-size:18px;line-height:1.5}.chip-row{display:flex;gap:8px;flex-wrap:wrap;margin-top:18px}.chip{padding:8px 11px;border-radius:999px;background:var(--mint);color:var(--green);font-size:11px;font-weight:850}
        .license{display:grid;grid-template-columns:1.05fr .95fr;gap:20px;margin-top:30px}.license-card{border:1px solid var(--line);background:#fff;border-radius:26px;padding:26px}.badge{display:inline-flex;padding:9px 12px;border-radius:999px;background:var(--mint);border:1px solid #9ed2c3;color:var(--green);font-size:11px;font-weight:900}.license-card ul{margin:18px 0 0;padding-left:19px;color:var(--muted);font-size:14px;line-height:1.65}.note{margin-top:17px;padding:14px;border-radius:16px;background:#f1f4f4;font-size:11px;line-height:1.55;color:#70777d}
        .loop{display:grid;grid-template-columns:repeat(6,1fr);gap:9px;margin-top:32px}.loop-card{position:relative;min-height:190px;border:1px solid var(--line);background:#fff;border-radius:20px;padding:19px}.loop-card b{font-size:10px;color:var(--green);letter-spacing:.13em}.loop-card h3{margin-top:12px;font-size:19px}.loop-card p{margin-top:8px;font-size:12px;line-height:1.5;color:var(--muted)}.loop-card:last-child{background:#eaf7f2;border-color:#9ed2c3}.loop-arrow{position:absolute;right:-13px;top:50%;transform:translateY(-50%);color:#7d878c;font-size:22px}
        .network{display:grid;grid-template-columns:1fr 1.2fr 1fr;gap:16px;align-items:center;margin-top:32px}.node-list{display:grid;gap:11px}.node{border:1px solid var(--line);border-radius:18px;background:#fff;padding:18px}.node b{display:block;font-size:15px}.node span{display:block;margin-top:6px;color:var(--muted);font-size:11px;line-height:1.4}.hub{min-height:280px;border:2px solid var(--green);border-radius:32px;background:linear-gradient(180deg,#edf9f4,#e3f2ed);display:grid;place-items:center;position:relative}.hub strong{font-size:40px;letter-spacing:-.04em;color:var(--green)}.hub small{position:absolute;bottom:28px;font-size:10px;color:#65736e}.arrow{font-size:25px;color:#869095;text-align:center}
        .projects{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-top:26px}.project{min-height:190px;display:flex;flex-direction:column;border:1px solid var(--line);border-radius:20px;padding:18px;background:#fff;text-decoration:none;color:inherit}.project.featured{background:#eaf7f2;border-color:#9ed2c3}.project:hover{transform:translateY(-2px);border-color:#8ac8b8}.project-role{font-size:10px;font-weight:800;color:#80898e;letter-spacing:.1em;text-transform:uppercase}.project strong{margin-top:8px;font-size:22px;letter-spacing:-.03em}.project-desc{margin-top:7px;font-size:12px;line-height:1.45;color:var(--muted)}.project-link{margin-top:auto;padding-top:14px;font-size:11px;font-weight:850;color:var(--green)}
        .evidence{display:grid;grid-template-columns:1.15fr .85fr;gap:18px;margin-top:30px}.darkpanel{border:1px solid #303a3c;background:var(--dark2);border-radius:24px;padding:24px}.metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.metric{border:1px solid #303a3c;border-radius:17px;padding:17px;background:#121718}.metric b{display:block;font-size:36px;letter-spacing:-.05em}.metric span{display:block;margin-top:6px;font-size:10px;line-height:1.4;color:#a1aaa9}.check{border-left:3px solid #73d3b7;padding-left:16px;margin-top:13px;color:#c7cfcd;font-size:13px;line-height:1.55}.evidence-source{margin-top:16px;font-size:10px;line-height:1.45;color:#8b9598}
        .takeaway{margin-top:32px;border:1px solid #9ed2c3;border-radius:26px;background:#eaf7f2;padding:28px;font-size:clamp(24px,3vw,48px);font-weight:900;letter-spacing:-.045em;line-height:1.15;color:#14332b}.cta{display:flex;gap:10px;flex-wrap:wrap;margin-top:28px}.btn{display:inline-flex;padding:12px 16px;border-radius:999px;text-decoration:none;border:1px solid var(--line);background:#fff;color:var(--ink);font-size:12px;font-weight:850}.btn.primary{background:var(--green);color:#fff;border-color:var(--green)}.dark .btn{background:#171d1e;border-color:#30393a;color:#f2f5f4}.dark .btn.primary{background:#43a98f;color:#07120e;border-color:#43a98f}.copyright{margin-top:16px;max-width:950px;font-size:10px;line-height:1.55;color:#858d92}.dark .copyright{color:#858f92}
        .toolbar{position:fixed;right:18px;bottom:18px;z-index:50;display:flex;gap:6px}.toolbar button{border:1px solid #cfd5d7;background:rgba(255,255,255,.94);border-radius:11px;padding:9px 11px;font-weight:800;cursor:pointer;box-shadow:0 4px 16px rgba(0,0,0,.08)}
        @media(max-width:1000px){.slide{aspect-ratio:auto;min-height:100svh;padding:30px 22px 24px}.hero,.grid2,.license,.network,.evidence{grid-template-columns:1fr}.stats{grid-template-columns:1fr}.loop{grid-template-columns:repeat(2,1fr)}.projects{grid-template-columns:repeat(2,1fr)}.metrics{grid-template-columns:1fr 1fr}.loop-arrow{display:none}}
        @media(max-width:620px){.projects,.loop{grid-template-columns:1fr}.metrics{grid-template-columns:1fr}.toolbar{display:none}}
        @media print{.toolbar{display:none}.slide{height:100vh;min-height:auto;width:100vw;break-after:page}.slide:last-of-type{break-after:auto}}
      `}</style>

      <div className="toolbar"><button onClick={() => window.scrollBy({ top: window.innerHeight * 0.92, behavior: 'smooth' })}>↓ Next</button><button onClick={() => document.documentElement.requestFullscreen?.()}>⛶ Fullscreen</button><button onClick={() => window.print()}>⎙ Print</button></div>

      <section className="slide"><div className="content hero"><div><div className="eyebrow">Why this portfolio exists · 2026</div><h1 style={{ marginTop: 18 }}>왜 지금,<br />이 OSS인가?</h1><p className="lead">Kubernetes와 플랫폼 엔지니어링이 표준화될수록 개별 도구보다 더 어려운 문제는 <b>그 사이의 경계와 운영 지식</b>입니다. 이 포트폴리오는 그 문제를 OSS로 분리하고 다시 연결한 기록입니다.</p></div><div className="orbit"><span className="orb o1">Standards</span><span className="orb o2">Platform</span><span className="orb o3">Data</span><span className="orb o4">AI / Edge</span><span className="orb o5">Operations</span><div className="core">OSS Portfolio</div></div></div><Footer no="01" text="From market signal → engineering response" /></section>

      <section className="slide"><div className="content"><div className="eyebrow">01 · Market signal</div><h2 style={{ marginTop: 15 }}>Kubernetes는 이미<br />“기반”이 되었습니다.</h2><p className="lead">이제 질문은 Kubernetes를 쓸 것인가가 아니라 그 위에 어떤 반복 가능한 플랫폼과 운영 체계를 만들 것인가에 가깝습니다.</p><div className="stats"><Stat value="82%" title="Kubernetes in production" detail="CNCF Annual Cloud Native Survey 2025: 컨테이너 사용 조직 중 production Kubernetes 사용 비율." href="https://www.cncf.io/reports/the-cncf-annual-cloud-native-survey/" /><Stat value="80%" title="Platform engineering teams" detail="Gartner 전망: 2026년까지 대형 소프트웨어 엔지니어링 조직의 80%가 플랫폼 엔지니어링 팀을 둘 것으로 전망." href="https://www.gartner.com/en/articles/what-is-platform-engineering" /><Stat value="~1B" title="OSS contributions" detail="GitHub Octoverse 2024: 2024년 공개·오픈소스 프로젝트에 거의 10억 건의 기여." href="https://github.blog/news-insights/octoverse/octoverse-2024/" /></div></div><Footer no="02" text="The infrastructure is becoming standard" /></section>

      <section className="slide"><div className="content"><div className="eyebrow">02 · The real problem</div><h2 style={{ marginTop: 15 }}>도구가 많아서 힘든 게 아니라,<br /><span style={{ color: 'var(--green)' }}>도구 사이의 경계</span>가 힘듭니다.</h2><div className="grid2"><div className="card"><strong>Integration seams</strong><p>Identity · DNS · TLS · networking · storage · GitOps · policy가 서로 다른 lifecycle을 가집니다.</p><div className="chip-row"><span className="chip">OIDC</span><span className="chip">TLS</span><span className="chip">DNS</span><span className="chip">Storage</span></div></div><div className="card"><strong>Operational memory</strong><p>장애·업그레이드·호환성의 해결책이 개인 경험으로 남으면 다음 변경에서 다시 비용이 발생합니다.</p><div className="chip-row"><span className="chip">Incident</span><span className="chip">Upgrade</span><span className="chip">Regression</span></div></div><div className="card"><strong>Reproducibility</strong><p>“내 환경에서는 된다”를 넘어 같은 baseline을 다시 만들고 검증할 수 있어야 합니다.</p></div><div className="card"><strong>Reuse</strong><p>좋은 해결책을 작은 OSS로 분리하면 팀과 프로젝트가 커져도 같은 패턴을 다시 사용할 수 있습니다.</p></div></div></div><Footer no="03" text="This is where the OSS portfolio starts" /></section>

      <section className="slide"><div className="content"><div className="eyebrow">03 · Adoption</div><h2 style={{ marginTop: 15 }}>오픈소스의 가치는<br /><span style={{ color: 'var(--green)' }}>읽을 수 있음</span>보다 <span style={{ color: 'var(--green)' }}>활용할 수 있음</span>에 있습니다.</h2><div className="license"><div className="license-card"><span className="badge">Apache License 2.0</span><h3 style={{ marginTop: 18 }}>Narwhal · Narwhal Portal</h3><ul><li>명시적인 오픈소스 라이선스로 소스·수정·배포 조건을 확인할 수 있습니다.</li><li>Apache-2.0의 라이선스·저작권·NOTICE 등의 요구사항을 확인해 재배포를 검토할 수 있습니다.</li><li>상업적 활용 가능 여부를 라이선스 관점에서 검토하기 쉬운 공개 저장소 구조입니다.</li></ul><div className="note">Apache-2.0이 “무조건 제약 없음”을 의미하는 것은 아닙니다. 실제 적용 시 저장소의 LICENSE·NOTICE와 포함된 제3자 의존성의 라이선스를 함께 검토해야 합니다.</div></div><div className="license-card"><h3>Adoption path</h3><div className="grid2" style={{ marginTop: 18, gap: 12 }}><div className="card"><strong>Explore</strong><p>문서·설계·라이선스 확인</p></div><div className="card"><strong>Adopt</strong><p>내 환경에 적용·검증</p></div><div className="card"><strong>Extend</strong><p>필요한 경계만 수정·확장</p></div><div className="card"><strong>Contribute</strong><p>개선 결과를 다시 환원</p></div></div></div></div></div><Footer no="04" text="Open source as an adoption surface" /></section>

      <section className="slide"><div className="content"><div className="eyebrow">04 · OpenForge</div><h2 style={{ marginTop: 15 }}>진짜 활용도는<br /><span style={{ color: 'var(--green)' }}>OpenForge에서 한 단계 더</span> 올라갑니다.</h2><p className="lead">프로젝트에서 얻은 insight를 한 번 쓰고 버리지 않습니다. 반복되는 패턴을 표준·템플릿·검증 절차로 바꿔 다음 OSS가 바로 재사용할 수 있게 합니다.</p><div className="loop">{[['01','Problem','실제 OSS에서 문제와 반복 패턴 발견'],['02','Evidence','incident · upgrade · CI · 운영 결과 축적'],['03','Standardize','OpenForge에 표준·ADR·정책으로 정리'],['04','Template','workflow · policy · K8s · GitOps 템플릿화'],['05','Apply','Narwhal·Beluga·각 OSS에 다시 적용'],['06','Improve','metrics와 다음 문제를 다시 OpenForge로 환류']].map((item,index)=><div className="loop-card" key={item[0]}><b>{item[0]}</b><h3>{item[1]}</h3><p>{item[2]}</p>{index < 5 && <span className="loop-arrow">→</span>}</div>)}</div><p className="lead" style={{ fontSize: 14, marginTop: 20 }}>OpenForge README에는 repository structure, documentation, GitHub workflows, CI/CD, security, supply-chain governance, change impact, upgrade/compatibility, AI-assisted engineering 등을 표준화하고, Project Lifecycle을 <b>Lessons / Metrics → OpenForge Improvement</b>로 연결하는 구조가 명시되어 있습니다.</p></div><Footer no="05" text="Insight becomes reusable engineering infrastructure" /></section>

      <section className="slide"><div className="content"><div className="eyebrow">05 · Portfolio map</div><h2 style={{ marginTop: 15 }}>각 OSS는 서로 다른 프로젝트지만,<br />하나의 <span style={{ color: 'var(--green)' }}>engineering system</span>으로 연결됩니다.</h2><div className="network"><div className="node-list"><div className="node"><b>OpenForge</b><span>standards · templates · governance</span></div><div className="node"><b>kube-ready-box</b><span>reproducible Kubernetes baseline</span></div></div><div className="hub"><strong>Narwhal</strong><small>integration · verification · operation</small></div><div className="node-list"><div className="node"><b>Beluga</b><span>data platform</span></div><div className="node"><b>KubeMetal</b><span>local AI / edge</span></div></div></div><div className="projects">{projects.map((item,index)=><ProjectCard item={item} key={item[0]} featured={index === 2 || index === 0} />)}</div></div><Footer no="06" text="Foundation → Platform → Data → Edge / Local AI" /></section>

      <section className="slide dark"><div className="content"><div className="eyebrow">06 · Evidence</div><h2 style={{ marginTop: 15 }}>“만들었다”가 아니라<br /><span style={{ color: '#75d2b7' }}>검증하고 다시 표준화했습니다.</span></h2><div className="evidence"><div className="darkpanel"><div className="metrics"><div className="metric"><b>35</b><span>Narwhal integrated applications</span></div><div className="metric"><b>51</b><span>regression checks in CI</span></div><div className="metric"><b>263</b><span>documented incidents / lessons</span></div></div><p className="evidence-source">Narwhal README의 현재 공개 상태를 요약한 프로젝트 지표입니다.</p></div><div className="darkpanel"><div className="check">Incident → Lesson → Discriminator → Regression test</div><div className="check">Project → reusable pattern → OpenForge standard</div><div className="check">License → documentation → reproducible adoption path</div></div></div></div><Footer no="07" text="Evidence closes the loop" /></section>

      <section className="slide dark"><div className="content" style={{ marginTop: 'auto', marginBottom: 'auto' }}><div className="eyebrow">07 · Takeaway</div><h2 style={{ marginTop: 15 }}>누군가 “이 OSS들은 뭐예요?”라고 묻는다면</h2><p className="lead">“Kubernetes 주변에서 이것저것 만든 프로젝트”가 아니라 이렇게 설명할 수 있습니다.</p><div className="takeaway">실제 플랫폼과 운영 문제에서 나온 해결책을 OSS로 만들고, OpenForge를 통해 반복되는 insight를 표준화해 다시 다음 프로젝트에 적용하는 engineering system입니다.</div><div className="cta"><a className="btn primary" href="https://github.com/dasomel/narwhal" target="_blank" rel="noreferrer">Narwhal ↗</a><a className="btn" href="https://github.com/dasomel/openforge" target="_blank" rel="noreferrer">OpenForge ↗</a><Link className="btn" href="/oss/">OSS Portfolio →</Link></div><p className="copyright">이 deck의 문구·레이아웃·CSS 인포그래픽은 본 사이트에서 새로 작성했습니다. 외부 사진·폰트 파일·제3자 로고 이미지는 포함하지 않습니다. 통계는 공개 출처를 링크하고, 프로젝트명·상표는 각 권리자에게 귀속될 수 있으며 개별 저장소의 라이선스가 적용됩니다.</p></div><Footer no="08" text="Original web deck · cne.io.kr" /></section>
    </main>
  );
}
