"use client";

const statSources = [
  { value: '82%', label: 'container users running Kubernetes in production', source: 'CNCF Annual Cloud Native Survey 2025/2026', href: 'https://www.cncf.io/reports/the-cncf-annual-cloud-native-survey/' },
  { value: '80%', label: 'large software organizations expected to establish platform teams by 2026', source: 'Gartner', href: 'https://www.gartner.com/en/articles/what-is-platform-engineering' },
  { value: '~1B', label: 'contributions to public & open source projects on GitHub in 2024', source: 'GitHub Octoverse 2024', href: 'https://github.blog/news-insights/octoverse/octoverse-2024/' },
];

const repos = [
  ['OpenForge','Engineering standards','반복 가능한 OSS 구조·문서·CI·공급망 기준','https://github.com/dasomel/openforge'],
  ['kube-ready-box','Kubernetes baseline','로컬/실험 Kubernetes 노드 베이스라인','https://github.com/dasomel/kube-ready-box'],
  ['Narwhal','Internal Developer Platform','GitOps·IAM·Mesh·Observability·Storage 등을 통합 운영','https://github.com/dasomel/narwhal'],
  ['Narwhal Portal','Platform UX','플랫폼 사용자가 클러스터와 서비스를 바라보는 운영 포털','https://github.com/dasomel/narwhal-portal'],
  ['nfs-quota-agent','Storage','NFS 기반 quota 운영 경계를 보완','https://github.com/dasomel/nfs-quota-agent'],
  ['ldapium','Identity','LDAP/Directory 경계를 단순화','https://github.com/dasomel/ldapium'],
  ['Beluga','Data Platform','CDC부터 lakehouse/query까지 데이터 lifecycle','https://github.com/dasomel/beluga'],
  ['KubeMetal','Edge / Local AI','Apple Silicon native compute + Kubernetes','https://github.com/dasomel/kubemetal'],
] as const;

function Source({ href, children }: { href: string; children: React.ReactNode }) {
  return <a className="source" href={href} target="_blank" rel="noreferrer">{children} ↗</a>;
}

function Repo({ item, focus = false }: { item: (typeof repos)[number]; focus?: boolean }) {
  return <a className={`repo ${focus ? 'focus' : ''}`} href={item[3]} target="_blank" rel="noreferrer"><span className="mini-dot"/><span className="repo-role">{item[1]}</span><strong>{item[0]}</strong><span className="repo-desc">{item[2]}</span><span className="repo-open">GitHub ↗</span></a>;
}

export default function OssStoryPage() {
  return (
    <main className="story">
      <style>{`
        :root{--ink:#111418;--muted:#687079;--line:#dfe4e7;--paper:#f6f7f4;--card:#fff;--accent:#08745c;--mint:#dff2eb;--dark:#0f1314;--dark2:#171c1d}
        *{box-sizing:border-box}html{scroll-behavior:smooth;background:var(--paper)}body{margin:0;background:var(--paper);font-family:ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:var(--ink)}
        .slide{width:min(100vw,1600px);min-height:100vh;aspect-ratio:16/9;margin:auto;padding:clamp(32px,5vw,82px);display:flex;flex-direction:column;justify-content:space-between;position:relative;overflow:hidden;background:var(--paper)}
        .dark{background:var(--dark);color:#f3f6f5}.dark::before,.slide::before{content:"";position:absolute;inset:0;pointer-events:none}.slide::before{background:radial-gradient(circle at 100% 0,rgba(8,116,92,.09),transparent 33%)}.dark::before{background:radial-gradient(circle at 80% 10%,rgba(48,177,141,.18),transparent 31%)}
        .content,.foot{position:relative;z-index:1}.eyebrow{font-size:11px;text-transform:uppercase;letter-spacing:.18em;font-weight:850;color:var(--accent)}.dark .eyebrow{color:#78d4b9}h1,h2,h3,p{margin:0}h1{font-size:clamp(46px,7vw,106px);line-height:.96;letter-spacing:-.055em;max-width:1150px}h2{font-size:clamp(34px,4.6vw,72px);line-height:1;letter-spacing:-.05em;max-width:1120px}h3{font-size:clamp(20px,2.1vw,31px)}.lead{margin-top:22px;max-width:940px;font-size:clamp(17px,1.55vw,24px);line-height:1.55;color:var(--muted)}.dark .lead{color:#bcc6c3}
        .source{color:inherit;text-decoration:none;border-bottom:1px solid currentColor}.source:hover{opacity:.72}.foot{display:flex;justify-content:space-between;gap:20px;color:#7a838a;font-size:11px}.dark .foot{color:#777f82}.num{font-variant-numeric:tabular-nums;font-weight:850;letter-spacing:.08em}
        .stat-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin-top:34px}.stat{border:1px solid var(--line);border-radius:26px;background:rgba(255,255,255,.8);padding:25px;position:relative;overflow:hidden}.stat::after{content:"";position:absolute;left:0;bottom:0;width:100%;height:5px;background:var(--accent)}.stat b{display:block;font-size:clamp(58px,6vw,100px);line-height:.95;letter-spacing:-.06em}.stat span{display:block;margin-top:13px;font-size:14px;line-height:1.45;color:var(--muted);min-height:44px}.stat small{display:block;margin-top:20px;font-size:10px;color:#8a9298;line-height:1.45}.thesis{margin-top:25px;border-left:4px solid var(--accent);padding:12px 0 12px 20px;font-size:clamp(20px,2.1vw,32px);line-height:1.3;letter-spacing:-.025em;max-width:1000px}
        .bars{display:grid;grid-template-columns:1fr;gap:14px;margin-top:34px;max-width:1100px}.bar-row{display:grid;grid-template-columns:230px 1fr 75px;gap:15px;align-items:center}.bar-label{font-size:13px;font-weight:750}.track{height:22px;background:#e5e9e9;border-radius:999px;overflow:hidden}.fill{height:100%;background:linear-gradient(90deg,var(--accent),#44a98f);border-radius:999px}.bar-value{font-size:18px;font-weight:850;text-align:right}.callout{border:1px solid var(--line);background:#fff;border-radius:24px;padding:24px;font-size:18px;line-height:1.45}.two{display:grid;grid-template-columns:1.1fr .9fr;gap:22px;margin-top:30px}.three{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin-top:30px}.iconbox{border:1px solid var(--line);border-radius:20px;background:#fff;padding:20px}.icon{width:44px;height:44px;border-radius:14px;background:var(--mint);display:grid;place-items:center;color:var(--accent);font-weight:900;margin-bottom:14px}.iconbox strong{display:block;font-size:18px}.iconbox p{margin-top:7px;font-size:13px;line-height:1.5;color:var(--muted)}
        .network{display:grid;grid-template-columns:1fr 1.2fr 1fr;gap:18px;align-items:center;margin-top:34px}.cluster{display:grid;gap:12px}.cluster .chip{border:1px solid var(--line);background:#fff;border-radius:18px;padding:15px 16px;font-weight:800;font-size:13px}.center{border:2px solid var(--accent);border-radius:34px;background:linear-gradient(180deg,#edf9f4,#e3f2ed);min-height:270px;display:grid;place-items:center;position:relative}.center::before{content:"";position:absolute;inset:15px;border:1px dashed rgba(8,116,92,.35);border-radius:27px}.center b{font-size:38px;letter-spacing:-.04em;color:var(--accent)}.arrow{font-size:25px;color:#879095;text-align:center}.center-note{position:absolute;bottom:28px;font-size:11px;color:#63706c}.dark .center{background:#13231f;border-color:#39a88d}.dark .center b{color:#79d7be}.dark .center::before{border-color:rgba(121,215,190,.26)}
        .repo-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-top:26px}.repo{display:flex;flex-direction:column;min-height:188px;border:1px solid var(--line);border-radius:20px;background:#fff;padding:18px;text-decoration:none;color:inherit;transition:transform .15s,border-color .15s}.repo:hover{transform:translateY(-3px);border-color:#8cc9ba}.repo.focus{background:#eaf7f2;border-color:#8dcbbb}.mini-dot{width:8px;height:8px;border-radius:50%;background:var(--accent)}.repo-role{font-size:10px;color:#81898f;text-transform:uppercase;letter-spacing:.11em;font-weight:800;margin-top:9px}.repo strong{font-size:22px;letter-spacing:-.03em;margin-top:8px}.repo-desc{font-size:12px;color:var(--muted);line-height:1.45;margin-top:7px}.repo-open{font-size:11px;font-weight:800;color:var(--accent);margin-top:auto;padding-top:15px}
        .evidence{display:grid;grid-template-columns:1fr 1fr;gap:18px;margin-top:32px}.darkpanel{background:var(--dark2);border:1px solid #2d3536;border-radius:24px;padding:25px}.sequence{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin-top:18px}.step{border:1px solid #364041;border-radius:16px;padding:15px;background:#121718}.step b{display:block;font-size:13px}.step span{display:block;margin-top:5px;font-size:11px;color:#9da8a5;line-height:1.35}.metric-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:11px}.metric{border:1px solid #30393a;border-radius:17px;padding:18px;background:#121718}.metric b{display:block;font-size:36px;letter-spacing:-.04em}.metric span{display:block;margin-top:6px;font-size:11px;color:#9da8a5;line-height:1.4}.badge-row{display:flex;flex-wrap:wrap;gap:8px;margin-top:20px}.badge{padding:8px 11px;border-radius:999px;border:1px solid #34403e;color:#bdc8c4;font-size:11px}
        .cta{display:flex;gap:10px;flex-wrap:wrap;margin-top:30px}.btn{padding:12px 16px;border-radius:999px;text-decoration:none;border:1px solid var(--line);background:#fff;color:var(--ink);font-size:13px;font-weight:850}.btn.primary{background:var(--accent);color:#fff;border-color:var(--accent)}.dark .btn{background:#171d1e;border-color:#30393a;color:#eef2f1}.dark .btn.primary{background:#43a98f;color:#06120e;border-color:#43a98f}
        .copyright{margin-top:17px;max-width:960px;color:#858d92;font-size:10.5px;line-height:1.55}.copyright strong{color:inherit}.tool{position:fixed;right:18px;bottom:18px;z-index:30;display:flex;gap:6px}.tool button{border:1px solid #cfd5d7;background:rgba(255,255,255,.93);border-radius:11px;padding:9px 11px;font-weight:800;cursor:pointer;box-shadow:0 4px 16px rgba(0,0,0,.08)}
        @media(max-width:1000px){.slide{aspect-ratio:auto;min-height:100svh;padding:30px 22px 26px}.stat-grid,.three,.evidence,.two,.network{grid-template-columns:1fr}.repo-grid{grid-template-columns:repeat(2,1fr)}.bar-row{grid-template-columns:155px 1fr 55px}.sequence{grid-template-columns:1fr 1fr}}
        @media(max-width:620px){.repo-grid{grid-template-columns:1fr}.bar-row{grid-template-columns:1fr}.bar-value{text-align:left}.tool{display:none}}
        @media print{.tool{display:none}.slide{break-after:page;height:100vh;min-height:auto;width:100vw}.slide:last-of-type{break-after:auto}}
      `}</style>

      <div className="tool"><button onClick={()=>window.scrollBy({top:window.innerHeight*.92,behavior:'smooth'})}>↓ Next</button><button onClick={()=>document.documentElement.requestFullscreen?.()}>⛶ Fullscreen</button><button onClick={()=>window.print()}>⎙ Print</button></div>

      <section className="slide">
        <div className="content"><div className="eyebrow">Why this portfolio exists · 2026</div><h1 style={{marginTop:18}}>Kubernetes는<br/>이미 인프라의<br/>공통 언어가 됐습니다.</h1><p className="lead">문제는 이제 “Kubernetes를 쓰느냐”가 아니라, 그 위의 수많은 시스템을 <b>어떻게 일관되게 통합하고 운영하느냐</b>입니다.</p><div className="stat-grid">{statSources.map(s=><div className="stat" key={s.value}><b>{s.value}</b><span>{s.label}</span><small><Source href={s.href}>{s.source}</Source></small></div>)}</div><div className="thesis">그래서 이 OSS 포트폴리오는 제품 목록이 아니라, <b>플랫폼 복잡도를 작은 재사용 단위로 분리한 engineering record</b>입니다.</div></div><div className="foot"><span>Public sources · latest verified August 2026</span><span className="num">01 / 08</span></div>
      </section>

      <section className="slide">
        <div className="content"><div className="eyebrow">01 · From adoption to complexity</div><h2 style={{marginTop:15}}>표준이 보편화될수록<br/>“통합”이 제품이 됩니다.</h2><p className="lead">Kubernetes 자체보다 더 어려운 것은 identity, network, certificates, storage, observability, GitOps, policy가 서로 어긋나지 않게 유지하는 일입니다.</p><div className="bars"><div className="bar-row"><span className="bar-label">Kubernetes production</span><div className="track"><div className="fill" style={{width:'82%'}}/></div><span className="bar-value">82%</span></div><div className="bar-row"><span className="bar-label">Platform teams by 2026</span><div className="track"><div className="fill" style={{width:'80%'}}/></div><span className="bar-value">80%</span></div><div className="bar-row"><span className="bar-label">Open-source ecosystem</span><div className="track"><div className="fill" style={{width:'100%'}}/></div><span className="bar-value">~1B</span></div></div><div className="three"><div className="iconbox"><div className="icon">01</div><strong>Integration seams</strong><p>서로 다른 제품 사이의 DNS·TLS·OIDC·network·storage 경계.</p></div><div className="iconbox"><div className="icon">02</div><strong>Cognitive load</strong><p>개발자가 플랫폼 내부의 모든 구현 세부사항을 알아야 하는 비용.</p></div><div className="iconbox"><div className="icon">03</div><strong>Repeatability</strong><p>한 번 해결한 운영 문제를 다음 설치·업그레이드에서도 다시 재현하지 않는 것.</p></div></div></div><div className="foot"><span>Statistics are context, not marketing claims.</span><span className="num">02 / 08</span></div>
      </section>

      <section className="slide dark">
        <div className="content"><div className="eyebrow">02 · The thesis</div><h2 style={{marginTop:15}}>그래서 “기능”보다<br/><span style={{color:'#78d4b9'}}>경계와 재현성</span>을 관리합니다.</h2><div className="two"><div className="darkpanel"><div className="eyebrow">The old model</div><p className="lead">Kubernetes + 수십 개의 독립 프로젝트 + 각 팀의 운영 지식</p><div className="badge-row"><span className="badge">“누가 이 설정을 바꿨지?”</span><span className="badge">“업그레이드하면 또 깨질까?”</span><span className="badge">“오프라인에서 설치할 수 있나?”</span></div></div><div className="darkpanel"><div className="eyebrow">The engineering model</div><p className="lead">작은 OSS → 통합 → 검증 → 문서화 → 다시 재사용</p><div className="badge-row"><span className="badge">Problem</span><span className="badge">Design</span><span className="badge">Evidence</span><span className="badge">Regression</span></div></div></div><div className="sequence"><div className="step"><b>Problem</b><span>실제 운영에서 반복된 문제</span></div><div className="step"><b>OSS</b><span>문제를 독립적인 단위로 분리</span></div><div className="step"><b>Narwhal</b><span>플랫폼 수준에서 통합</span></div><div className="step"><b>Evidence</b><span>테스트·문서·운영 기록으로 재현</span></div></div></div><div className="foot"><span>Portfolio logic: problem → reusable capability → platform → evidence.</span><span className="num">03 / 08</span></div>
      </section>

      <section className="slide"><div className="content"><div className="eyebrow">03 · Portfolio map</div><h2 style={{marginTop:15}}>여러 저장소가 있지만<br/>하나의 engineering story입니다.</h2><p className="lead">Foundation에서 시작해 Platform을 만들고, Data와 Local AI까지 확장합니다. 각각 독립된 OSS이지만 같은 문제를 다른 경계에서 해결합니다.</p><div className="network"><div className="cluster"><div className="chip">OpenForge · standards</div><div className="chip">kube-ready-box · baseline</div></div><div className="center"><b>Narwhal</b><span className="center-note">integration · verification · operation</span></div><div className="cluster"><div className="chip">Beluga · data platform</div><div className="chip">KubeMetal · local AI</div></div></div></div><div className="foot"><span>Relation does not imply runtime dependency.</span><span className="num">04 / 08</span></div></section>

      <section className="slide"><div className="content"><div className="eyebrow">04 · Narwhal</div><h2 style={{marginTop:15}}>Narwhal은<br/>통합의 중심입니다.</h2><div className="repo-grid" style={{marginTop:36}}><Repo item={repos[0]}/><Repo item={repos[1]}/><Repo item={repos[2]} focus/><Repo item={repos[3]}/></div><div className="callout" style={{marginTop:20}}><b>핵심 관점:</b> Kubernetes 설치가 끝난 뒤 발생하는 “프로젝트 사이의 seams”를 하나의 플랫폼 운영 단위로 다룹니다.</div></div><div className="foot"><span>Narwhal: open-source, reproducible Kubernetes Internal Developer Platform</span><span className="num">05 / 08</span></div></section>

      <section className="slide dark"><div className="content"><div className="eyebrow">05 · Evidence</div><h2 style={{marginTop:15}}>실패를 지우지 않고<br/>다음 배포의 자산으로 만듭니다.</h2><div className="evidence"><div className="darkpanel"><p className="lead">Narwhal README 기준으로 통합 과정에서 발생한 incident를 기록하고, 그 원인과 discriminator를 다시 regression check로 연결합니다.</p><div className="sequence"><div className="step"><b>Incident</b><span>운영에서 실제 발생</span></div><div className="step"><b>Lesson</b><span>원인과 해결 기록</span></div><div className="step"><b>Discriminator</b><span>비슷한 원인과 구별</span></div><div className="step"><b>Regression</b><span>다음 변경에서 재검증</span></div></div></div><div className="metric-grid"><div className="metric"><b>483</b><span>commits since 2026-02-08</span></div><div className="metric"><b>51</b><span>regression checks in CI</span></div><div className="metric"><b>263</b><span>documented incidents</span></div></div></div><p className="copyright">프로젝트 상태 수치는 Narwhal README의 현재 공개 내용을 요약한 것입니다. 버전·커밋·검증 범위는 저장소가 변경되면 달라질 수 있습니다.</p></div><div className="foot"><span>Evidence over screenshots.</span><span className="num">06 / 08</span></div></section>

      <section className="slide"><div className="content"><div className="eyebrow">06 · The surrounding OSS</div><h2 style={{marginTop:15}}>Narwhal 주변에도<br/>각자의 “한 가지 문제”가 있습니다.</h2><div className="repo-grid"><Repo item={repos[4]}/><Repo item={repos[5]}/><Repo item={repos[6]}/><Repo item={repos[7]}/></div><div className="three"><div className="iconbox"><div className="icon">S</div><strong>Storage</strong><p>nfs-quota-agent로 storage enforcement 경계를 보완.</p></div><div className="iconbox"><div className="icon">I</div><strong>Identity</strong><p>ldapium으로 directory integration을 단순화.</p></div><div className="iconbox"><div className="icon">D</div><strong>Data / AI</strong><p>Beluga와 KubeMetal로 플랫폼 바깥의 실험 공간까지 연결.</p></div></div></div><div className="foot"><span>Small problems, reusable boundaries.</span><span className="num">07 / 08</span></div></section>

      <section className="slide dark"><div className="content" style={{marginTop:'auto',marginBottom:'auto'}}><div className="eyebrow">07 · Explore the work</div><h2 style={{marginTop:15}}>“그래서 이 OSS들은<br/>결국 무엇을 보여주나요?”</h2><p className="lead">Kubernetes를 설치할 줄 안다는 것보다, 그 위에서 <b>통합·검증·운영·문서화</b>가 반복될 수 있는 구조를 만드는 것이 이 포트폴리오의 핵심입니다.</p><div className="cta"><a className="btn primary" href="/oss/">OSS Portfolio ↗</a><a className="btn" href="https://github.com/dasomel/narwhal" target="_blank" rel="noreferrer">Narwhal ↗</a><a className="btn" href="https://github.com/dasomel" target="_blank" rel="noreferrer">GitHub / dasomel ↗</a></div><p className="copyright"><strong>Copyright & attribution.</strong> 이 deck의 문구·레이아웃·CSS/SVG 인포그래픽은 본 사이트에서 새로 작성했습니다. 외부 이미지·폰트 파일·제3자 로고 이미지는 사용하지 않았습니다. 통계는 CNCF, Gartner, GitHub의 공개 자료를 출처 링크와 함께 표기하고, 프로젝트 내용은 각 저장소를 요약했습니다. 프로젝트명·상표권은 각 권리자에게 있으며 개별 저장소의 라이선스가 적용됩니다.</p></div><div className="foot"><span>Original web-deck · no external media assets</span><span className="num">08 / 08</span></div></section>
    </main>
  );
}
