'use client';

const repos = [
  ['OpenForge', 'Engineering standards', '표준·템플릿·CI·보안·공급망·변경영향·운영 insight를 재사용 가능한 기준으로 환원'],
  ['kube-ready-box', 'Kubernetes baseline', '재현 가능한 Kubernetes 노드 기반을 제공하고 Narwhal의 실행 기반과 연결'],
  ['Narwhal', 'Internal Developer Platform', 'GitOps·IAM·Mesh·Observability·Registry·Storage·Backup·Policy를 하나의 운영 단위로 통합'],
  ['Narwhal Portal', 'Platform experience', '플랫폼 사용자가 클러스터와 서비스를 탐색하고 운영하는 관리 경험'],
  ['nfs-quota-agent', 'Storage enforcement', 'NFS 기반 영속 스토리지의 quota 운영을 독립 컴포넌트로 보완'],
  ['ldapium', 'Identity infrastructure', 'LDAP/Directory 경계를 단순화해 플랫폼 identity와 연결'],
  ['Beluga', 'Data platform', 'CDC부터 lakehouse·query까지 데이터 운영 흐름을 실험하고 정리'],
  ['KubeMetal', 'Local AI / Edge', 'Apple Silicon native compute와 Kubernetes control plane을 결합'],
];

const source = {
  cncf: 'CNCF Annual Cloud Native Survey, 2026-01-20',
  gartner: 'Gartner, Platform Engineering, 2026 outlook',
  github: 'GitHub Octoverse 2024',
  narwhal: 'dasomel/narwhal README / LICENSE',
  openforge: 'dasomel/openforge README',
};

function Stat({ value, label, detail }: { value: string; label: string; detail: string }) {
  return <div className="stat"><div className="stat-value">{value}</div><div className="stat-label">{label}</div><div className="stat-detail">{detail}</div></div>;
}

function Footer({ no, text = '' }: { no: string; text?: string }) {
  return <div className="footer"><span>{text}</span><b>{no} / 08</b></div>;
}

export default function OssStory() {
  return (
    <main className="deck">
      <style>{`
        :root{--ink:#101214;--muted:#697078;--line:#dfe3e6;--paper:#f7f7f4;--card:#fff;--green:#0b6b57;--green2:#dff2eb;--dark:#111416;--dark2:#171c1f}
        *{box-sizing:border-box}html{scroll-behavior:smooth;background:var(--paper)}body{margin:0;background:var(--paper);color:var(--ink);font-family:ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}
        .deck{width:100%}.slide{position:relative;width:min(100vw,1600px);min-height:100vh;aspect-ratio:16/9;margin:0 auto;padding:clamp(30px,5vw,82px);overflow:hidden;display:flex;flex-direction:column;justify-content:space-between;background:var(--paper)}
        .dark{background:var(--dark);color:#f4f6f6}.slide:before{content:"";position:absolute;inset:0;background:linear-gradient(135deg,rgba(11,107,87,.08),transparent 45%);pointer-events:none}.dark:before{background:radial-gradient(circle at 78% 20%,rgba(44,168,133,.18),transparent 28%)}
        .content{position:relative;z-index:1}.eyebrow{font-size:11px;font-weight:800;letter-spacing:.17em;text-transform:uppercase;color:var(--green)}.dark .eyebrow{color:#7ad4b9}
        h1,h2,h3,p{margin:0}h1{font-size:clamp(48px,7vw,108px);line-height:.96;letter-spacing:-.055em;max-width:1100px}h2{font-size:clamp(35px,4.8vw,72px);line-height:1;letter-spacing:-.05em;max-width:1150px}h3{font-size:clamp(19px,2vw,30px)}
        .lead{margin-top:22px;max-width:940px;font-size:clamp(17px,1.55vw,25px);line-height:1.55;color:var(--muted)}.dark .lead{color:#c2c8cb}.tiny{font-size:11px;line-height:1.5;color:#81878d}.dark .tiny{color:#8b9499}
        .hero{display:grid;grid-template-columns:1.15fr .85fr;gap:34px;align-items:center;height:100%}.hero-art{min-height:360px;border:1px solid rgba(11,107,87,.2);background:linear-gradient(160deg,#eef8f4,#e4f0ec);border-radius:32px;padding:32px;display:grid;place-items:center}
        .orbit{position:relative;width:min(88%,470px);aspect-ratio:1;border:2px solid #0b6b57;border-radius:50%}.core{position:absolute;left:50%;top:50%;transform:translate(-50%,-50%);padding:24px 32px;border-radius:18px;background:#0b6b57;color:white;font-size:24px;font-weight:900;box-shadow:0 18px 55px rgba(11,107,87,.2)}.orb{position:absolute;padding:9px 12px;border:1px solid rgba(11,107,87,.24);border-radius:999px;background:#fbfffd;font-size:12px;font-weight:800}.o1{top:5%;left:25%}.o2{top:28%;right:-3%}.o3{bottom:16%;right:7%}.o4{bottom:4%;left:23%}.o5{top:30%;left:-7%}
        .stats{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin-top:34px}.stat{border:1px solid var(--line);background:rgba(255,255,255,.76);border-radius:24px;padding:24px;min-height:220px}.stat-value{font-size:clamp(48px,5vw,78px);font-weight:900;letter-spacing:-.06em;color:var(--green)}.stat-label{margin-top:8px;font-size:15px;font-weight:800}.stat-detail{margin-top:10px;font-size:13px;line-height:1.5;color:var(--muted)}
        .problem-grid{display:grid;grid-template-columns:1fr 1fr;gap:18px;margin-top:32px}.problem{border-radius:24px;padding:24px;border:1px solid var(--line);background:#fff}.problem strong{display:block;font-size:11px;letter-spacing:.14em;text-transform:uppercase;color:var(--green)}.problem p{margin-top:10px;font-size:18px;line-height:1.5}.bridge{margin-top:24px;display:grid;grid-template-columns:1fr auto 1fr auto 1fr;align-items:center;gap:12px}.node{border:1px solid var(--line);border-radius:20px;padding:20px;background:#fff;min-height:120px}.node b{display:block}.node span{display:block;margin-top:8px;font-size:12px;color:var(--muted);line-height:1.45}.arrow{font-size:25px;color:#8a9298}
        .license{display:grid;grid-template-columns:1.05fr .95fr;gap:22px;margin-top:30px}.license-card{background:#fff;border:1px solid var(--line);border-radius:28px;padding:28px}.license-badge{display:inline-flex;align-items:center;gap:8px;padding:9px 12px;border-radius:999px;border:1px solid #9ed2c3;background:var(--green2);color:var(--green);font-size:12px;font-weight:900}.license-card ul{margin:20px 0 0;padding-left:19px;color:var(--muted);line-height:1.7;font-size:14px}.license-note{margin-top:18px;padding:15px;border-radius:16px;background:#f3f5f5;font-size:11px;line-height:1.6;color:#70777d}
        .loop{display:grid;grid-template-columns:repeat(6,1fr);gap:10px;margin-top:34px;align-items:stretch}.loop-card{border:1px solid var(--line);background:#fff;border-radius:20px;padding:20px;min-height:190px;position:relative}.loop-card b{display:block;color:var(--green);font-size:11px;text-transform:uppercase;letter-spacing:.12em}.loop-card h3{margin-top:14px;font-size:19px}.loop-card p{margin-top:9px;font-size:12px;line-height:1.5;color:var(--muted)}.loop-card:last-child{border-color:#9ed2c3;background:#ebf7f2}.loop-arrow{position:absolute;right:-14px;top:50%;transform:translateY(-50%);z-index:2;color:#7c858b}
        .portfolio{display:grid;grid-template-columns:repeat(2,1fr);gap:12px;margin-top:28px}.repo{border:1px solid var(--line);background:#fff;border-radius:20px;padding:18px}.repo .r-top{display:flex;justify-content:space-between;gap:12px;font-size:10px;color:#7b8389;text-transform:uppercase;letter-spacing:.1em;font-weight:800}.repo h3{margin-top:7px;font-size:22px}.repo p{margin-top:7px;font-size:12px;line-height:1.5;color:var(--muted)}
        .evidence{display:grid;grid-template-columns:1.2fr .8fr;gap:20px;margin-top:28px}.dark .ev{border-color:#30383d;background:var(--dark2)}.ev{border:1px solid var(--line);border-radius:24px;padding:24px;background:#fff}.ev-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.ev-num{font-size:42px;font-weight:900;letter-spacing:-.06em;color:var(--green)}.ev-label{margin-top:5px;font-size:11px;line-height:1.4;color:var(--muted)}.dark .ev-label{color:#9da5aa}.check{border-left:3px solid #74d3b8;padding-left:16px;margin-top:14px;font-size:14px;line-height:1.55;color:#c4cbce}.dark .check{color:#c4cbce}
        .cta{display:flex;gap:10px;flex-wrap:wrap;margin-top:28px}.btn{display:inline-flex;text-decoration:none;padding:12px 16px;border-radius:999px;border:1px solid var(--line);background:#fff;color:var(--ink);font-size:12px;font-weight:900}.btn.primary{background:var(--green);color:#fff;border-color:var(--green)}.dark .btn{background:#1a1f22;color:#f4f6f6;border-color:#30383d}.dark .btn.primary{background:#2b9d80;color:#07120f;border-color:#2b9d80}
        .footer{position:relative;z-index:1;display:flex;justify-content:space-between;gap:20px;font-size:10px;color:#7a8187}.dark .footer{color:#7f898e}.footer b{letter-spacing:.09em}
        .source{margin-top:18px;font-size:10px;line-height:1.45;color:#858b90;max-width:1000px}.dark .source{color:#81898e}
        .toolbar{position:fixed;right:18px;bottom:18px;z-index:100;display:flex;gap:6px}.toolbar button{border:1px solid #cfd4d7;background:rgba(255,255,255,.94);border-radius:12px;padding:9px 11px;font-weight:800;cursor:pointer;box-shadow:0 4px 16px rgba(0,0,0,.08)}
        @media(max-width:900px){.slide{aspect-ratio:auto;min-height:100svh;padding:30px 22px 24px}.hero,.license,.evidence{grid-template-columns:1fr}.stats{grid-template-columns:1fr}.problem-grid{grid-template-columns:1fr}.bridge{grid-template-columns:1fr}.arrow{display:none}.loop{grid-template-columns:1fr 1fr}.portfolio{grid-template-columns:1fr}.ev-grid{grid-template-columns:1fr 1fr}}
        @media print{.toolbar{display:none}.slide{height:100vh;min-height:auto;width:100vw;break-after:page}.slide:last-of-type{break-after:auto}}
      `}</style>

      <div className="toolbar"><button onClick={()=>window.scrollBy({top:window.innerHeight*.92,behavior:'smooth'})}>↓ Next</button><button onClick={()=>document.documentElement.requestFullscreen?.()}>⛶ Fullscreen</button><button onClick={()=>window.print()}>⎙ Print</button></div>

      <section className="slide"><div className="content hero">
        <div><div className="eyebrow">Open Source Portfolio · dasomel</div><h1 style={{marginTop:18}}>왜 지금,<br/>이 OSS인가?</h1><p className="lead">Kubernetes와 플랫폼 엔지니어링이 표준화될수록, 개별 도구보다 더 어려운 문제는 그 사이의 경계와 운영 지식입니다. 이 포트폴리오는 그 문제를 OSS로 쪼개고 다시 연결한 기록입니다.</p></div>
        <div className="hero-art"><div className="orbit"><span className="orb o1">Standards</span><span className="orb o2">Platform</span><span className="orb o3">Data</span><span className="orb o4">AI / Edge</span><span className="orb o5">Operations</span><div className="core">OSS Portfolio</div></div></div>
      </div><Footer no="01" text="From market signal → engineering response"/></section>

      <section className="slide"><div className="content"><div className="eyebrow">01 · Market signal</div><h2 style={{marginTop:15}}>Kubernetes는 이미<br/>“기반”이 되었습니다.</h2><p className="lead">이제 질문은 Kubernetes를 쓸 것인가가 아니라, 그 위에 어떤 반복 가능한 플랫폼과 운영 체계를 만들 것인가에 가까워졌습니다.</p><div className="stats"><Stat value="82%" label="Kubernetes in production" detail="2025 CNCF Annual Cloud Native Survey. 컨테이너 사용 조직 가운데 production Kubernetes 사용 비율."/><Stat value="80%" label="Platform engineering teams" detail="Gartner는 2026년까지 대형 소프트웨어 엔지니어링 조직의 80%가 플랫폼 엔지니어링 팀을 둘 것으로 전망."/><Stat value="≈1B" label="OSS contributions" detail="GitHub Octoverse 2024: 2024년 공개·오픈소스 프로젝트에 거의 10억 건의 기여."/></div><p className="source">Sources: {source.cncf}; {source.gartner}; {source.github}.</p></div><Footer no="02" text="The infrastructure is becoming standard"/></section>

      <section className="slide"><div className="content"><div className="eyebrow">02 · The real problem</div><h2 style={{marginTop:15}}>도구가 많아서 힘든 게 아니라,<br/><span style={{color:'var(--green)'}}>도구 사이의 경계</span>가 힘듭니다.</h2><div className="problem-grid"><div className="problem"><strong>Integration seams</strong><p>Identity · DNS · TLS · networking · storage · GitOps · policy가 서로 다른 lifecycle을 가집니다.</p></div><div className="problem"><strong>Operational memory</strong><p>한 번 해결한 장애와 upgrade 호환성 문제를 다음 릴리스에서도 다시 만나기 쉽습니다.</p></div><div className="problem"><strong>Reproducibility</strong><p>“내 환경에서는 된다”를 넘어 같은 baseline을 다시 만들고 검증해야 합니다.</p></div><div className="problem"><strong>Reuse</strong><p>좋은 해결책이 개인의 경험으로 끝나면 팀과 프로젝트가 커질수록 비용이 다시 발생합니다.</p></div></div></div><Footer no="03" text="This is where the OSS portfolio starts"/></section>

      <section className="slide"><div className="content"><div className="eyebrow">03 · Adoption</div><h2 style={{marginTop:15}}>오픈소스의 가치는<br/><span style={{color:'var(--green)'}}>읽을 수 있음</span>보다 <span style={{color:'var(--green)'}}>활용할 수 있음</span>에 있습니다.</h2><div className="license"><div className="license-card"><span className="license-badge">Apache License 2.0</span><h3 style={{marginTop:20}}>Narwhal · Narwhal Portal</h3><ul><li>소스·수정·배포를 검토할 수 있는 명시적 라이선스</li><li>Apache-2.0의 조건에 따라 재배포 시 라이선스·저작권·NOTICE 등의 요구사항을 확인</li><li>상업적 활용 가능 여부를 라이선스 관점에서 검토하기 쉬운 형태</li></ul><div className="license-note">주의: “Apache-2.0 = 무조건 제약 없음”은 아닙니다. 저장소의 LICENSE·NOTICE와 포함된 제3자 의존성의 라이선스를 함께 확인해야 합니다.</div></div><div className="license-card"><h3>Adoption path</h3><div className="bridge" style={{gridTemplateColumns:'1fr auto 1fr'}}><div className="node"><b>Explore</b><span>문서와 설계를 읽고 문제 적합성 확인</span></div><div className="arrow">→</div><div className="node"><b>Adopt</b><span>내 환경에 적용·수정·검증·운영</span></div></div><div className="bridge" style={{gridTemplateColumns:'1fr auto 1fr'}}><div className="node"><b>Fork / Extend</b><span>필요한 경계만 확장</span></div><div className="arrow">→</div><div className="node"><b>Contribute</b><span>다시 OSS 생태계로 환원</span></div></div></div></div><p className="source">Source: Narwhal LICENSE / Apache License 2.0. Not legal advice — repository and dependency license notices should be reviewed for each deployment.</p></div><Footer no="04" text="Open source as an adoption surface"/></section>

      <section className="slide"><div className="content"><div className="eyebrow">04 · OpenForge</div><h2 style={{marginTop:15}}>그런데 진짜 활용도는<br/><span style={{color:'var(--green)'}}>OpenForge</span>에서 한 단계 더 올라갑니다.</h2><p className="lead">프로젝트에서 얻은 engineering insight를 한 번 쓰고 버리지 않습니다. 반복되는 패턴을 표준·템플릿·검증 절차로 바꿔 다음 OSS가 바로 재사용할 수 있게 합니다.</p><div className="loop">{[['01','Problem','실제 OSS에서 문제와 반복 패턴 발견'],['02','Evidence','incident · upgrade · CI · 운영 결과 축적'],['03','Standardize','OpenForge에 표준·ADR·정책으로 정리'],['04','Template','workflow · policy · k8s · GitOps 템플릿화'],['05','Apply','Narwhal·Beluga·각 OSS에 다시 적용'],['06','Improve','다음 문제와 metrics를 다시 OpenForge로 환류']].map((x,i)=><div className="loop-card" key={x[0]}><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p>{i<5&&<span className="loop-arrow">→</span>}</div>)}</div><p className="source">OpenForge는 repository structure, documentation, GitHub workflows, CI/CD, security, supply-chain governance, change impact, upgrade/compatibility, AI-assisted engineering 등 반복되는 OSS engineering 요소를 표준화하고, project lifecycle을 Lessons / Metrics → OpenForge Improvement로 연결합니다. cite-placeholder: OpenForge README</p></div><Footer no="05" text="Insight becomes reusable engineering infrastructure"/></section>

      <section className="slide"><div className="content"><div className="eyebrow">05 · Portfolio map</div><h2 style={{marginTop:15}}>각 OSS는 서로 다른 제품이지만,<br/>하나의 <span style={{color:'var(--green)'}}>engineering system</span>으로 연결됩니다.</h2><div className="bridge"><div className="node"><b>OpenForge</b><span>standards · templates · governance</span></div><div className="arrow">→</div><div className="node primary"><b>kube-ready-box</b><span>reproducible Kubernetes baseline</span></div><div className="arrow">→</div><div className="node primary"><b>Narwhal</b><span>integrated IDP</span></div></div><div className="portfolio">{repos.map(([name,role,desc])=><div className="repo" key={name}><div className="r-top"><span>{role}</span><span>OSS</span></div><h3>{name}</h3><p>{desc}</p></div>)}</div></div><Footer no="06" text="Foundation → Platform → Data → Edge / Local AI"/></section>

      <section className="slide dark"><div className="content"><div className="eyebrow">06 · Evidence</div><h2 style={{marginTop:15}}>“만들었다”가 아니라<br/><span style={{color:'#75d2b7'}}>검증하고 다시 표준화했다.</span></h2><div className="evidence"><div className="ev"><div className="ev-grid"><div><div className="ev-num">35</div><div className="ev-label">Narwhal integrated GitOps-managed applications</div></div><div><div className="ev-num">51</div><div className="ev-label">regression checks in the Narwhal CI suite</div></div><div><div className="ev-num">263</div><div className="ev-label">documented incidents / lessons used as regression knowledge</div></div></div></div><div className="ev"><div className="check">Incident → Lesson → Discriminator → Regression test</div><div className="check">Project → reusable pattern → OpenForge standard</div><div className="check">License → documentation → reproducible adoption path</div></div></div><p className="source">Project evidence: Narwhal README and repository documentation. The counts shown here are maintained in the project documentation and should be treated as current-project metrics, not industry statistics.</p></div><Footer no="07" text="Evidence closes the loop"/></section>

      <section className="slide"><div className="content"><div className="eyebrow">07 · Takeaway</div><h2 style={{marginTop:15}}>누군가 “이 OSS들은 뭐예요?”라고 묻는다면</h2><p className="lead">대답은 “Kubernetes 주변에서 이것저것 만든 프로젝트들”이 아닙니다.</p><div style={{marginTop:34,padding:'30px',borderRadius:28,border:'1px solid #9ed2c3',background:'#ebf7f2'}}><div style={{fontSize:'clamp(25px,3vw,48px)',fontWeight:900,letterSpacing:'-.04em',lineHeight:1.15}}>“실제 플랫폼과 운영 문제에서 나온 해결책을 OSS로 만들고,<br/>OpenForge를 통해 반복되는 insight를 표준화해 다시 다음 프로젝트에 적용하는 engineering system입니다.”</div></div><div className="cta"><a className="btn primary" href="https://github.com/dasomel/narwhal" target="_blank" rel="noreferrer">Narwhal ↗</a><a className="btn" href="https://github.com/dasomel/openforge" target="_blank" rel="noreferrer">OpenForge ↗</a><a className="btn" href="/oss/">OSS Portfolio →</a></div><p className="source">Design note: this deck uses CSS/SVG-style diagrams and text only; no third-party photos, icons, logos, or font files are embedded.</p></div><Footer no="08" text="Open source portfolio · cne.io.kr"/></section>
    </main>
  );
}
