import Link from 'next/link';
import { Rss, ArrowUpRight } from 'lucide-react';
import { getTranslations } from 'next-intl/server';
import { getNotes } from '@/lib/content';
import { routing } from '@/i18n/routing';

export function generateStaticParams(){return routing.locales.map(locale=>({locale}))}
export async function generateMetadata({params}:{params:Promise<{locale:string}>}){const{locale}=await params;const t=await getTranslations({locale,namespace:'notes'});return{title:t('title'),description:t('subtitle')}}

export default async function NotesPage({params}:{params:Promise<{locale:string}>}){
  const {locale}=await params; const lang=locale as 'ko'|'en'; const posts=getNotes(lang); const base=lang==='en'?'/en':'/ko'; const rss=lang==='en'?'/rss-en.xml':'/rss.xml'; const featured=posts[0]; const rest=posts.slice(1);
  return <main>
    <section className="border-b" style={{borderColor:'var(--border)'}}><div className="mx-auto max-w-[1440px] px-5 py-14 sm:px-8 lg:px-16 lg:py-20"><div className="flex items-center justify-between gap-4"><div className="font-mono text-xs font-semibold tracking-[0.14em]" style={{color:'var(--accent)'}}>KNOWLEDGE / FIELD NOTES</div><Link href={rss} className="inline-flex items-center gap-2 rounded-full border px-3 py-2 font-mono text-[10px]" style={{borderColor:'var(--border)',color:'var(--text-muted)'}}><Rss className="h-3.5 w-3.5"/> RSS</Link></div><h1 className="mt-5 max-w-5xl text-4xl font-semibold tracking-[-0.055em] sm:text-6xl" style={{color:'var(--text)'}}>{lang==='en'?<>Notes produced by<br/>real engineering work.</>:<>실제 엔지니어링에서<br/>나온 기록만 남깁니다.</>}</h1><p className="mt-6 max-w-4xl text-base leading-8 sm:text-lg" style={{color:'var(--text-muted)'}}>{lang==='en'?'Architecture decisions, integration seams, troubleshooting, operational lessons and design changes. Notes are evidence of how a system was understood, not just content to publish.':'아키텍처 의사결정, 시스템 경계의 통합 문제, 트러블슈팅, 운영 교훈과 설계 변경을 기록합니다. 글 자체보다 시스템을 어떻게 이해하고 판단했는지 남기는 것이 목적입니다.'}</p></div></section>
    {featured&&<section className="mx-auto max-w-[1440px] px-5 py-12 sm:px-8 lg:px-16"><div className="grid gap-8 lg:grid-cols-[.65fr_1.35fr]"><div><div className="font-mono text-[10px] font-semibold tracking-[0.13em]" style={{color:'var(--signal)'}}>FEATURED FIELD NOTE</div><div className="mt-3 font-mono text-[10px]" style={{color:'var(--text-faint)'}}>{featured.pubDate.slice(0,10)} · {featured.tags.slice(0,3).join(' · ')}</div></div><Link href={`${base}/posts/${featured.slug}`} className="group"><h2 className="text-3xl font-semibold tracking-[-0.04em] group-hover:text-[var(--accent)] sm:text-4xl" style={{color:'var(--text)'}}>{featured.title}</h2>{featured.description&&<p className="mt-4 max-w-4xl text-base leading-7" style={{color:'var(--text-muted)'}}>{featured.description}</p>}<span className="mt-5 inline-flex items-center gap-2 text-sm font-semibold" style={{color:'var(--accent)'}}>Read note <ArrowUpRight className="h-4 w-4"/></span></Link></div></section>}
    <section className="border-y" style={{borderColor:'var(--border)',backgroundColor:'var(--surface-hi)'}}><div className="mx-auto max-w-[1440px] px-5 py-12 sm:px-8 lg:px-16"><div className="flex flex-wrap items-end justify-between gap-4"><div><div className="font-mono text-[10px] font-semibold tracking-[0.13em]" style={{color:'var(--accent)'}}>NOTE INDEX</div><h2 className="mt-3 text-3xl font-semibold tracking-[-0.04em]" style={{color:'var(--text)'}}>{lang==='en'?'Read by evidence, not by card.':'카드가 아니라 기록의 흐름으로 읽습니다.'}</h2></div><Link href={`${base}/knowledge`} className="text-sm" style={{color:'var(--accent)'}}>Knowledge hub →</Link></div><div className="mt-8 divide-y" style={{borderColor:'var(--border)'}}>{rest.map((post,i)=><Link key={post.slug} href={`${base}/posts/${post.slug}`} className="group grid gap-2 py-6 first:pt-0 md:grid-cols-[72px_160px_1fr_1.2fr_auto] md:items-start" style={{borderColor:'var(--border)'}}><div className="font-mono text-[9px]" style={{color:'var(--text-faint)'}}>{String(i+2).padStart(2,'0')}</div><div className="font-mono text-[10px]" style={{color:'var(--text-faint)'}}>{post.pubDate.slice(0,10)}</div><div><h3 className="text-lg font-semibold group-hover:text-[var(--accent)]" style={{color:'var(--text)'}}>{post.title}</h3><div className="mt-2 font-mono text-[9px]" style={{color:'var(--accent)'}}>{post.tags.slice(0,3).join(' · ')}</div></div><p className="line-clamp-3 text-sm leading-6" style={{color:'var(--text-muted)'}}>{post.description||''}</p><ArrowUpRight className="hidden h-4 w-4 md:block" style={{color:'var(--text-faint)'}}/></Link>)}</div></div></section>
    <section className="mx-auto max-w-[1440px] px-5 py-10 sm:px-8 lg:px-16"><div className="font-mono text-[10px] font-semibold tracking-[0.13em]" style={{color:'var(--accent)'}}>TOPICS / SYSTEM CONTEXT</div><p className="mt-3 text-sm leading-6" style={{color:'var(--text-muted)'}}>Kubernetes · Platform Engineering · Open Source · AI-assisted Development · Reliability · Architecture · Troubleshooting · Design System</p></section>
  </main>
}
