import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import Link from 'next/link';
import { ArrowLeft, ArrowUpRight, Github } from 'lucide-react';
import { getProjects, getProjectBySlug, getNotes, getDocs, getTechDigests } from '@/lib/content';
import { MDXContent } from '@/components/MDXContent';
import { ProjectSourceSnapshot } from '@/components/projects/ProjectSourceSnapshot';
import { ArchitectureDiagram } from '@/components/visual/ArchitectureDiagram';
import { ProjectVisual } from '@/components/visual/ProjectVisual';
import { ProjectArchitectureImage } from '@/components/visual/ProjectArchitectureImage';
import { EvidenceRail } from '@/components/visual/EvidenceRail';
import { routing } from '@/i18n/routing';
import { Button } from '@/components/ui/button';

export function generateStaticParams(){const params:{locale:string;slug:string}[]=[];routing.locales.forEach(locale=>getProjects(locale as 'ko'|'en').forEach(project=>params.push({locale,slug:project.slug})));return params}
export async function generateMetadata({params}:{params:Promise<{locale:string;slug:string}>}):Promise<Metadata>{const{locale,slug}=await params;const lang=locale as 'ko'|'en';const result=getProjectBySlug(slug,lang);if(!result)return{};const{meta}=result;return{title:meta.title,description:meta.description,alternates:{canonical:`https://cne.io.kr/${lang}/projects/${slug}`}}}
const narwhalSignals=[{value:'35',label:'GitOps-managed applications',detail:'Desired platform state under GitOps'},{value:'51',label:'CI regression checks',detail:'Integration behavior protected in CI'},{value:'263',label:'integration / incident lessons',detail:'Failures retained as engineering knowledge'},{value:'120+',label:'cluster checks',detail:'Repeatable platform verification'}] as const;
const readingOrder=['Problem','Architecture','Development','Proof','Knowledge','Record'] as const;
const quotaDocs={ko:[['개요','/ko/docs/nfs-quota-agent/overview'],['아키텍처','/ko/docs/nfs-quota-agent/architecture'],['기능 및 CRD','/ko/docs/nfs-quota-agent/feature-guide'],['설치 및 설정','/ko/docs/nfs-quota-agent/getting-started'],['기능 상세','/ko/docs/nfs-quota-agent/features'],['웹 UI','/ko/docs/nfs-quota-agent/web-ui'],['운영 및 모니터링','/ko/docs/nfs-quota-agent/operations']],en:[['Overview','/en/docs/nfs-quota-agent/overview'],['Architecture','/en/docs/nfs-quota-agent/architecture'],['Features & CRD','/en/docs/nfs-quota-agent/feature-guide'],['Getting started','/en/docs/nfs-quota-agent/getting-started'],['Feature guide','/en/docs/nfs-quota-agent/features'],['Web UI','/en/docs/nfs-quota-agent/web-ui'],['Operations','/en/docs/nfs-quota-agent/operations']]} as const;
const quotaScreenshots=[['01-dashboard-quotas.png','Quotas dashboard','전체 PV 쿼터와 사용량 상태'],['02-orphans.png','Orphans','고아 디렉터리와 정리 유예 상태'],['03-trends.png','Trends','사용량 증가 추이'],['04-policies.png','Policies','네임스페이스별 정책 적용 결과'],['05-audit-logs.png','Audit logs','쿼터 변경 감사 로그']] as const;

export default async function ProjectPage({params}:{params:Promise<{locale:string;slug:string}>}){const{locale,slug}=await params;const lang=locale as 'ko'|'en';const result=getProjectBySlug(slug,lang);if(!result)notFound();const{meta,content}=result;const base=lang==='en'?'/en':'/ko';const notes=getNotes(lang),docs=getDocs(lang),digests=getTechDigests(lang);const terms=new Set([slug.toLowerCase(),meta.title.toLowerCase(),...meta.tags.map(t=>t.toLowerCase())]);const explicit=notes.filter(n=>n.projects?.includes(slug));const relatedNotes=(explicit.length?explicit:notes.filter(n=>[...n.tags,n.title,n.description??''].some(v=>{const x=v.toLowerCase();return terms.has(x)||x.includes(slug.toLowerCase())||x.includes(meta.title.toLowerCase())}))).slice(0,4);const relatedDocs=docs.filter(d=>{const h=`${d.project} ${d.slug} ${d.title}`.toLowerCase();return h.includes(slug.toLowerCase())||h.includes(meta.title.toLowerCase())}).slice(0,6);const relatedDigests=digests.filter(d=>d.projects?.includes(slug)).slice(0,4);const genericSignals=[{value:String(meta.tags.length),label:'technology / domain signals',detail:'Declared scope and technical context'},{value:String(relatedDocs.length),label:'connected docs',detail:'Operational or implementation documentation'},{value:String(relatedNotes.length),label:'engineering notes',detail:'Knowledge produced by the project'},{value:String(relatedDigests.length),label:'digest links',detail:'External signals explicitly connected'}] as const;const signals=slug==='narwhal'?narwhalSignals:genericSignals;
return <main>
<div className="mx-auto max-w-[1440px] px-5 pt-7 sm:px-8 lg:px-16"><Link href={`${base}/projects`} className="inline-flex items-center gap-2 text-sm" style={{color:'var(--text-muted)'}}><ArrowLeft className="h-4 w-4"/>{lang==='en'?'All systems':'전체 시스템'}</Link></div>
<header className="mx-auto grid max-w-[1440px] gap-8 px-5 pb-9 pt-8 sm:px-8 lg:grid-cols-[1fr_auto] lg:px-16"><div><div className="font-mono text-xs font-medium tracking-[0.12em]" style={{color:'var(--accent)'}}>WORK / {meta.featured?'ACTIVE SYSTEM':'ENGINEERING RECORD'}</div><h1 className="mt-4 text-5xl font-semibold tracking-[-0.055em] sm:text-6xl" style={{color:'var(--text)'}}>{meta.title}</h1><p className="mt-5 max-w-4xl text-base leading-8 sm:text-lg" style={{color:'var(--text-muted)'}}>{meta.description}</p><div className="mt-5 font-mono text-[10px] uppercase leading-6 tracking-[0.08em]" style={{color:'var(--text-faint)'}}>{meta.tags.join(' · ')}</div></div>{meta.github&&<div className="lg:pt-9"><Button asChild size="sm"><a href={meta.github} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2"><Github className="h-4 w-4"/>Source <ArrowUpRight className="h-3 w-3"/></a></Button></div>}</header>
<section className="border-y" style={{borderColor:'var(--border)',backgroundColor:'var(--surface-hi)'}}><div className="mx-auto max-w-[1440px] px-5 py-5 sm:px-8 lg:px-16"><div className="flex flex-wrap gap-x-5 gap-y-3">{readingOrder.map((item,i)=><span key={item} className="font-mono text-[9px] uppercase tracking-[0.09em]" style={{color:i===2?'var(--signal)':'var(--text-faint)'}}>{String(i+1).padStart(2,'0')} / {item}</span>)}</div>{slug==='nfs-quota-agent'&&<nav aria-label={lang==='en'?'NFS Quota Agent documentation':'NFS Quota Agent 문서'} className="mt-5 flex flex-wrap gap-2">{quotaDocs[lang].map(([label,href],i)=><Link key={href} href={href} className="rounded-full border px-3 py-1.5 text-xs transition-colors hover:border-[var(--accent)] hover:text-[var(--accent)]" style={{borderColor:i===0?'var(--accent)':'var(--border)',color:i===0?'var(--accent)':'var(--text-muted)'}}>{label}</Link>)}</nav>}</div></section>
{(meta.problem||meta.solution)&&<section><div className="mx-auto grid max-w-[1440px] gap-8 px-5 py-11 sm:px-8 lg:grid-cols-2 lg:px-16">{meta.problem&&<EditorialBlock title="01 / PROBLEM" text={meta.problem} tone="var(--signal)"/>}{meta.solution&&<EditorialBlock title="RESPONSE" text={meta.solution} tone="var(--accent)"/>}</div></section>}
<section className="border-y" style={{borderColor:'var(--border)',backgroundColor:'var(--surface-hi)'}}><div className="mx-auto max-w-[1440px] px-5 py-12 sm:px-8 lg:px-16"><div className="font-mono text-[10px] font-semibold tracking-[0.13em]" style={{color:'var(--accent-2)'}}>02 / ARCHITECTURE</div><h2 className="mt-3 max-w-3xl text-3xl font-semibold tracking-[-0.04em]" style={{color:'var(--text)'}}>{lang==='en'?'Read the boundaries before the features.':'기능보다 먼저 경계와 연결을 봅니다.'}</h2><p className="mt-3 max-w-3xl text-sm leading-6" style={{color:'var(--text-muted)'}}>{lang==='en'?'Identity, delivery, network, storage and workload integration are shown as operational seams rather than a feature inventory.':'Identity, Delivery, Network, Storage, Workload 통합을 기능 목록이 아니라 운영 경계로 읽습니다.'}</p><div className="mt-7 space-y-5"><ProjectArchitectureImage slug={slug}/><ArchitectureDiagram slug={slug}/><ProjectVisual slug={slug}/></div></div></section>
{slug==='nfs-quota-agent'&&<section className="border-b" style={{borderColor:'var(--border)'}}><div className="mx-auto max-w-[1440px] px-5 py-12 sm:px-8 lg:px-16"><div className="font-mono text-[10px] font-semibold tracking-[0.13em]" style={{color:'var(--signal)'}}>02A / OPERATOR VIEW</div><div className="mt-3 flex flex-wrap items-end justify-between gap-4"><div><h2 className="text-3xl font-semibold tracking-[-0.04em]" style={{color:'var(--text)'}}>{lang==='en'?'The dashboard makes enforcement visible.':'적용된 쿼터를 화면에서 확인합니다.'}</h2><p className="mt-3 max-w-2xl text-sm leading-6" style={{color:'var(--text-muted)'}}>{lang==='en'?'Five built-in views connect quota state, cleanup, growth, policy and audit evidence.':'쿼터 상태, 정리 대상, 사용량 증가, 정책, 감사 이력을 하나의 운영 화면에서 연결합니다.'}</p></div><Link href={`${base}/docs/nfs-quota-agent/web-ui`} className="text-sm font-semibold" style={{color:'var(--accent)'}}>{lang==='en'?'Read the Web UI guide':'웹 UI 가이드 보기'} ↗</Link></div><div className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{quotaScreenshots.map(([file,title,caption])=><figure key={file} className="overflow-hidden rounded-2xl border" style={{borderColor:'var(--border)',backgroundColor:'var(--surface-hi)'}}><img src={`/images/nfs-quota-agent/${file}`} alt={`${title} screenshot`} loading="lazy" className="h-auto w-full"/><figcaption className="border-t px-4 py-3" style={{borderColor:'var(--border)'}}><div className="text-sm font-semibold" style={{color:'var(--text)'}}>{title}</div><div className="mt-1 text-xs" style={{color:'var(--text-muted)'}}>{caption}</div></figcaption></figure>)}</div></div></section>}
{meta.github&&<section className="mx-auto max-w-[1440px] px-5 py-11 sm:px-8 lg:px-16"><div className="grid gap-6 lg:grid-cols-[260px_1fr]"><div><div className="font-mono text-[10px] font-semibold tracking-[0.13em]" style={{color:'var(--signal)'}}>03 / DEVELOPMENT OVER TIME</div><h2 className="mt-3 text-2xl font-semibold tracking-[-0.035em]" style={{color:'var(--text)'}}>{lang==='en'?'Evolution is part of the evidence.':'계속 발전하는 과정도 evidence입니다.'}</h2><p className="mt-3 text-sm leading-6" style={{color:'var(--text-muted)'}}>{lang==='en'?'First commit, cumulative commits, releases and recent activity show whether the system is still being engineered.':'첫 commit, 누적 commit, release와 최근 활동으로 시스템이 지금도 개발되고 있는지 보여줍니다.'}</p></div><ProjectSourceSnapshot github={meta.github} lang={lang}/></div></section>}
<EvidenceRail items={signals} title="04 / PROOF, NOT BADGES"/>
{(relatedDocs.length>0||relatedNotes.length>0||relatedDigests.length>0)&&<section className="border-y" style={{borderColor:'var(--border)',backgroundColor:'var(--surface-hi)'}}><div className="mx-auto max-w-[1440px] px-5 py-11 sm:px-8 lg:px-16"><div className="font-mono text-[10px] font-semibold tracking-[0.13em]" style={{color:'var(--accent)'}}>05 / CONNECTED KNOWLEDGE</div><h2 className="mt-3 text-3xl font-semibold tracking-[-0.04em]" style={{color:'var(--text)'}}>{lang==='en'?'What this system produced beyond code':'코드 밖에 남은 엔지니어링 지식'}</h2><div className="mt-7 grid gap-8 lg:grid-cols-3">{relatedDocs.length>0&&<EvidenceGroup title="Docs" items={relatedDocs.map(d=>({href:`${base}/docs/${d.slug}`,title:d.title,meta:d.description}))}/>} {relatedNotes.length>0&&<EvidenceGroup title="Field Notes" items={relatedNotes.map(n=>({href:`${base}/posts/${n.slug}`,title:n.title,meta:n.pubDate.slice(0,10)}))}/>} {relatedDigests.length>0&&<EvidenceGroup title="Signals" items={relatedDigests.map(d=>({href:`${base}/posts/${d.slug}`,title:d.title,meta:d.pubDate.slice(0,10)}))}/>}</div></div></section>}
<section><div className="mx-auto max-w-[920px] px-5 pb-5 pt-12 sm:px-8"><div className="font-mono text-[10px] font-semibold tracking-[0.13em]" style={{color:'var(--text-faint)'}}>06 / ENGINEERING RECORD</div><p className="mt-2 text-sm" style={{color:'var(--text-muted)'}}>{lang==='en'?'Implementation details, operating notes and project-specific context.':'구현 세부사항, 운영 기록과 프로젝트별 맥락을 이어서 봅니다.'}</p></div><article className="cne-doc-prose prose prose-lg mx-auto max-w-[920px] px-5 pb-16 sm:px-8 prose-headings:font-semibold"><MDXContent source={content}/></article></section>
</main>}

function EditorialBlock({title,text,tone}:{title:string;text:string;tone:string}){return <div className="border-l pl-5" style={{borderColor:tone}}><div className="font-mono text-[10px] font-semibold tracking-[0.1em]" style={{color:tone}}>{title}</div><p className="mt-4 text-base leading-8" style={{color:'var(--text-muted)'}}>{text}</p></div>}
function EvidenceGroup({title,items}:{title:string;items:{href:string;title:string;meta?:string}[]}){return <div><div className="font-mono text-[10px] font-semibold tracking-[0.1em]" style={{color:'var(--text-faint)'}}>{title.toUpperCase()}</div><div className="mt-3 divide-y" style={{borderColor:'var(--border)'}}>{items.map(item=><Link key={item.href} href={item.href} className="group flex items-start justify-between gap-3 py-4 first:pt-0"><div><div className="text-sm font-semibold group-hover:text-[var(--accent)]" style={{color:'var(--text)'}}>{item.title}</div>{item.meta&&<div className="mt-1 line-clamp-2 text-xs leading-5" style={{color:'var(--text-muted)'}}>{item.meta}</div>}</div><ArrowUpRight className="mt-0.5 h-3.5 w-3.5 shrink-0" style={{color:'var(--text-faint)'}}/></Link>)}</div></div>}
