import type { Metadata } from 'next';
import Link from 'next/link';
import { ArrowUpRight } from 'lucide-react';
import { routing } from '@/i18n/routing';
import { getNotes, getProjects } from '@/lib/content';
import { EngineeringLabMap } from '@/components/visual/EngineeringLabMap';
import { EvidenceRail } from '@/components/visual/EvidenceRail';

export function generateStaticParams(){return routing.locales.map(locale=>({locale}))}
export async function generateMetadata({params}:{params:Promise<{locale:string}>}):Promise<Metadata>{const{locale}=await params;const lang=locale as 'ko'|'en';const description=lang==='en'?'A living engineering lab for Cloud Native, platform engineering and open source systems.':'Cloud Native, Platform Engineering, OSS 시스템을 직접 만들고 검증하며 공개하는 Open Engineering Lab.';return{title:'dasomel — Open Engineering Lab',description,alternates:{canonical:`https://cne.io.kr/${lang}`,languages:{ko:'https://cne.io.kr/ko',en:'https://cne.io.kr/en'}}}}
const evidence=[{value:'11+',label:'OSS systems',detail:'Connected as one engineering portfolio'},{value:'35',label:'Narwhal GitOps apps',detail:'Desired platform state under GitOps'},{value:'51',label:'CI regression checks',detail:'Integration behavior protected in CI'},{value:'263',label:'integration / incident lessons',detail:'Operational knowledge kept as evidence'}] as const;
const featured=[{slug:'narwhal',label:'PLATFORM ENGINEERING',fallback:'Kubernetes Internal Developer Platform · GitOps · SSO · Service Mesh · Observability'},{slug:'beluga',label:'DATA PLATFORM',fallback:'CDC → Kafka → Flink → Iceberg → Trino → Superset on Kubernetes'},{slug:'kubemetal',label:'AI / EDGE',fallback:'Apple Silicon local MLOps · K3s control plane + macOS GPU workloads'}]as const;

export default async function HomePage({params}:{params:Promise<{locale:string}>}){const{locale}=await params;const lang=locale as 'ko'|'en';const base=lang==='en'?'/en':'/ko';const projects=getProjects(lang),notes=getNotes(lang).slice(0,4);const selected=featured.map(item=>{const p=projects.find(x=>x.slug===item.slug);return{...item,title:p?.title??item.slug,description:p?.description||p?.problem||item.fallback}});const copy=lang==='en'?{kicker:'OPEN ENGINEERING LAB',title:<>I build platforms,<br/>then publish what survives.</>,lead:'Cloud Native, platform engineering, data and AI/edge systems are treated as one connected engineering practice: build a real system, verify the seams, document the decisions, and share reusable knowledge.',work:'Selected systems',knowledge:'Knowledge from the work',story:'How the judgement evolved'}:{kicker:'OPEN ENGINEERING LAB',title:<>플랫폼을 직접 만들고,<br/>검증을 통과한 것을 공개합니다.</>,lead:'Cloud Native, Platform Engineering, Data, AI/Edge를 서로 분리된 기술이 아니라 하나의 engineering practice로 다룹니다. 실제 시스템을 만들고, 경계를 검증하고, 의사결정을 기록하고, 재사용 가능한 지식으로 공유합니다.',work:'대표 시스템',knowledge:'시스템에서 나온 지식',story:'판단 기준이 어떻게 변해왔는가'};return <main>
<section className="border-b" style={{borderColor:'var(--border)'}}><div className="mx-auto max-w-[1440px] px-5 py-14 sm:px-8 sm:py-18 lg:px-16 lg:py-24"><div className="font-mono text-xs font-semibold tracking-[0.14em]" style={{color:'var(--accent)'}}>{copy.kicker}</div><h1 className="mt-5 max-w-5xl text-4xl font-semibold tracking-[-0.06em] sm:text-6xl lg:text-[4.6rem] lg:leading-[1.02]" style={{color:'var(--text)'}}>{copy.title}</h1><p className="mt-7 max-w-4xl text-base leading-8 sm:text-lg" style={{color:'var(--text-muted)'}}>{copy.lead}</p><div className="mt-8 flex flex-wrap gap-3"><Link href={`${base}/projects`} className="inline-flex items-center gap-2 rounded-full border px-4 py-2 text-sm font-semibold" style={{borderColor:'var(--accent)',color:'var(--accent)',background:'var(--accent-dim)'}}>Explore Work <ArrowUpRight className="h-4 w-4"/></Link><Link href={`${base}/knowledge`} className="inline-flex items-center gap-2 rounded-full border px-4 py-2 text-sm" style={{borderColor:'var(--border)',color:'var(--text-muted)'}}>Browse Knowledge</Link></div></div></section>
<EvidenceRail items={evidence}/>
<section className="mx-auto max-w-[1440px] px-5 py-12 sm:px-8 sm:py-16 lg:px-16"><EngineeringLabMap base={base}/></section>
<section className="mx-auto max-w-[1440px] px-5 pb-14 sm:px-8 sm:pb-18 lg:px-16"><div className="flex items-end justify-between gap-5"><div><div className="font-mono text-[10px] font-semibold tracking-[0.13em]" style={{color:'var(--accent)'}}>SELECTED WORK</div><h2 className="mt-3 text-3xl font-semibold tracking-[-0.04em] sm:text-4xl" style={{color:'var(--text)'}}>{copy.work}</h2></div><Link href={`${base}/projects`} className="hidden items-center gap-1 text-sm sm:inline-flex" style={{color:'var(--accent)'}}>All systems <ArrowUpRight className="h-4 w-4"/></Link></div><div className="mt-8 divide-y" style={{borderColor:'var(--border)'}}>{selected.map((p,i)=><Link key={p.slug} href={`${base}/projects/${p.slug}`} className="group grid gap-3 py-7 first:pt-0 lg:grid-cols-[120px_1fr_1.2fr_auto] lg:items-start" style={{borderColor:'var(--border)'}}><div className="font-mono text-[10px] tracking-[0.1em]" style={{color:i===2?'var(--signal)':'var(--accent)'}}>{p.label}</div><div className="text-2xl font-semibold tracking-[-0.03em] group-hover:text-[var(--accent)]" style={{color:'var(--text)'}}>{p.title}</div><p className="text-sm leading-6" style={{color:'var(--text-muted)'}}>{p.description}</p><ArrowUpRight className="hidden h-4 w-4 lg:block" style={{color:'var(--text-faint)'}}/></Link>)}</div></section>
<section className="border-y" style={{borderColor:'var(--border)',backgroundColor:'var(--surface-hi)'}}><div className="mx-auto max-w-[1440px] px-5 py-14 sm:px-8 lg:px-16"><div className="grid gap-10 lg:grid-cols-[.7fr_1.3fr]"><div><div className="font-mono text-[10px] font-semibold tracking-[0.13em]" style={{color:'var(--accent)'}}>KNOWLEDGE PROVENANCE</div><h2 className="mt-3 text-3xl font-semibold tracking-[-0.04em]" style={{color:'var(--text)'}}>{copy.knowledge}</h2><p className="mt-4 text-sm leading-6" style={{color:'var(--text-muted)'}}>{lang==='en'?'Field notes, architecture, troubleshooting, research and talks stay connected to the systems that produced them.':'필드 노트, 아키텍처, 트러블슈팅, 리서치와 발표를 그것을 만들어낸 시스템과 연결해 둡니다.'}</p><Link href={`${base}/knowledge`} className="mt-6 inline-flex items-center gap-2 text-sm font-semibold" style={{color:'var(--accent)'}}>Open Knowledge <ArrowUpRight className="h-4 w-4"/></Link></div><div className="divide-y" style={{borderColor:'var(--border)'}}>{notes.map(n=><Link key={n.slug} href={`${base}/posts/${n.slug}`} className="group block py-5 first:pt-0" style={{borderColor:'var(--border)'}}><div className="font-mono text-[9px] uppercase tracking-[0.08em]" style={{color:'var(--text-faint)'}}>{n.projects?.length?n.projects.join(' · '):'Workbench note'}</div><div className="mt-2 text-lg font-semibold group-hover:text-[var(--accent)]" style={{color:'var(--text)'}}>{n.title}</div>{n.description&&<p className="mt-2 line-clamp-2 text-sm leading-6" style={{color:'var(--text-muted)'}}>{n.description}</p>}</Link>)}</div></div></div></section>
<section className="mx-auto max-w-[1440px] px-5 py-14 sm:px-8 lg:px-16"><div className="font-mono text-[10px] font-semibold tracking-[0.13em]" style={{color:'var(--signal)'}}>STORY</div><Link href={`${base}/oss/story`} className="group mt-3 grid gap-4 lg:grid-cols-[1fr_auto] lg:items-end"><div><h2 className="text-3xl font-semibold tracking-[-0.04em] group-hover:text-[var(--accent)] sm:text-4xl" style={{color:'var(--text)'}}>{copy.story}</h2><p className="mt-3 max-w-3xl text-sm leading-6" style={{color:'var(--text-muted)'}}>{lang==='en'?'Framework → DevOps → Cloud Native → Platform → OSS → AI-assisted engineering. The tools changed; the operating principles became clearer.':'Framework → DevOps → Cloud Native → Platform → OSS → AI-assisted engineering. 기술은 바뀌었지만, 운영 원칙은 더 명확해졌습니다.'}</p></div><ArrowUpRight className="h-6 w-6" style={{color:'var(--accent)'}}/></Link></section>
</main>}
