import type { Metadata } from 'next';
import Link from 'next/link';
import { ArrowUpRight } from 'lucide-react';
import { routing } from '@/i18n/routing';
import { getNotes, getProjects } from '@/lib/content';
import { EcosystemInfographic } from '@/components/visual/EcosystemInfographic';

export function generateStaticParams() { return routing.locales.map(locale => ({ locale })); }
export async function generateMetadata({ params }: { params: Promise<{ locale: string }> }): Promise<Metadata> { const { locale } = await params; const lang=locale as 'ko'|'en'; const url=`https://cne.io.kr/${lang}`; const description=lang==='en'?'An engineering workbench for building, testing, learning, and sharing what survives in Cloud Native and open source.':'Cloud Native와 OSS를 직접 만들고 검증하며 배우는 엔지니어링 작업 기록.'; return {title:'dasomel — OSS Workbench',description,alternates:{canonical:url,languages:{ko:'https://cne.io.kr/ko',en:'https://cne.io.kr/en'}}}; }
const evidence=[['11+','OSS projects'],['35','Narwhal GitOps apps'],['51','CI regression checks'],['263','integration / incident lessons']] as const;
const featured=[{slug:'narwhal',label:'IDP',fallback:'Kubernetes Internal Developer Platform · GitOps · SSO · Service Mesh · Observability'},{slug:'beluga',label:'DATA',fallback:'CDC → Kafka → Flink → Iceberg → Trino → Superset on Kubernetes'},{slug:'kubemetal',label:'AI / EDGE',fallback:'Apple Silicon local MLOps · K3s control plane + macOS GPU workloads'}] as const;
export default async function HomePage({params}:{params:Promise<{locale:string}>}){const{locale}=await params;const lang=locale as 'ko'|'en';const base=lang==='en'?'/en':'/ko';const projects=getProjects(lang);const notes=getNotes(lang).slice(0,4);const copy=lang==='en'?{hero:'Kubernetes, Cloud Native, Platform Engineering, AI-assisted development, and the engineering knowledge learned by building and operating open source systems.',selected:'Systems I am building now',recent:'Recent notes',story:'Read the journey through turning points and lessons, not a list of technologies.'}:{hero:'Kubernetes, Cloud Native, Platform Engineering, AI-assisted development, 그리고 오픈소스를 직접 만들고 운영하며 얻은 engineering knowledge를 기록합니다.',selected:'지금 만들고 있는 시스템',recent:'최근 기록',story:'기술 스택의 나열보다 전환점과 배운 것을 중심으로 보는 Story.'};const selectedProjects=featured.map(item=>{const project=projects.find(p=>p.slug===item.slug);return{...item,title:project?.title??item.slug,description:project?.description||project?.problem||item.fallback}});return <main>
<section className="border-b" style={{borderColor:'var(--border)'}}><div className="mx-auto max-w-[1440px] px-5 py-12 sm:px-8 sm:py-16 lg:px-16 lg:py-20"><div className="font-mono text-xs font-medium tracking-[0.12em]" style={{color:'var(--accent)'}}>CLOUD NATIVE / OSS WORKBENCH</div><h1 className="mt-5 max-w-5xl text-4xl font-semibold tracking-[-0.055em] sm:text-6xl lg:text-[4rem] lg:leading-[1.06]" style={{color:'var(--text)'}}>Build. Test. Learn.<br/>Share what survives.</h1><p className="mt-6 max-w-5xl text-base leading-7 sm:text-lg sm:leading-8" style={{color:'var(--text-muted)'}}>{copy.hero}</p><div className="mt-6 font-mono text-[10px] tracking-[0.12em] sm:text-xs" style={{color:'var(--text-faint)'}}>BUILD IN PUBLIC · VERIFY WITH EVIDENCE · LEARN FROM FAILURES</div></div></section>
<section style={{backgroundColor:'var(--surface-hi)'}}><div className="mx-auto grid max-w-[1440px] grid-cols-2 gap-x-5 gap-y-6 px-5 py-7 sm:px-8 lg:grid-cols-4 lg:px-16">{evidence.map(([value,label])=><div key={label}><div className="text-2xl font-semibold sm:text-3xl" style={{color:'var(--text)'}}>{value}</div><div className="mt-1 font-mono text-[10px] uppercase tracking-[0.08em]" style={{color:'var(--text-faint)'}}>{label}</div></div>)}</div></section>
<section className="mx-auto max-w-[1440px] px-5 py-12 sm:px-8 sm:py-14 lg:px-16"><EcosystemInfographic lang={lang}/></section>
<section className="mx-auto max-w-[1440px] px-5 pb-12 sm:px-8 sm:pb-14 lg:px-16"><div className="font-mono text-[11px] tracking-[0.1em]" style={{color:'var(--accent)'}}>SELECTED OSS</div><div className="mt-3 flex items-end justify-between gap-4"><h2 className="text-2xl font-semibold sm:text-3xl" style={{color:'var(--text)'}}>{copy.selected}</h2><Link href={`${base}/projects`} className="hidden items-center gap-1 text-xs font-medium sm:inline-flex" style={{color:'var(--accent)'}}>View all <ArrowUpRight className="h-3.5 w-3.5"/></Link></div><div className="mt-6 grid gap-4 lg:grid-cols-3">{selectedProjects.map(project=><Link key={project.slug} href={`${base}/projects/${project.slug}`} className="group rounded-2xl border p-5 transition-transform hover:-translate-y-1" style={{borderColor:'var(--border)',backgroundColor:'var(--surface)'}}><div className="font-mono text-[10px] tracking-[0.1em]" style={{color:'var(--accent)'}}>{project.label}</div><div className="mt-2 text-xl font-semibold group-hover:text-[var(--accent)]" style={{color:'var(--text)'}}>{project.title}</div><p className="mt-2 text-sm leading-6" style={{color:'var(--text-muted)'}}>{project.description}</p></Link>)}</div></section>
<section className="border-y" style={{borderColor:'var(--border)',backgroundColor:'var(--surface-hi)'}}><div className="mx-auto max-w-[1440px] px-5 py-12 sm:px-8 sm:py-14 lg:px-16"><div className="font-mono text-[11px] tracking-[0.1em]" style={{color:'var(--accent)'}}>ENGINEERING NOTES</div><h2 className="mt-3 text-2xl font-semibold sm:text-3xl" style={{color:'var(--text)'}}>{copy.recent}</h2><div className="mt-6 space-y-3">{notes.map(note=><Link key={note.slug} href={`${base}/posts/${note.slug}`} className="group flex items-start justify-between gap-4 rounded-xl border px-4 py-4 sm:px-5" style={{borderColor:'var(--border)',backgroundColor:'var(--surface)'}}><div className="min-w-0"><div className="text-base font-semibold group-hover:text-[var(--accent)] sm:text-lg" style={{color:'var(--text)'}}>{note.title}</div>{note.description&&<p className="mt-1 line-clamp-2 text-sm leading-6" style={{color:'var(--text-muted)'}}>{note.description}</p>}</div><ArrowUpRight className="mt-1 h-4 w-4 shrink-0" style={{color:'var(--text-faint)'}}/></Link>)}</div></div></section>
<section className="mx-auto max-w-[1440px] px-5 py-12 sm:px-8 sm:py-14 lg:px-16"><div className="font-mono text-[11px] tracking-[0.1em]" style={{color:'var(--accent)'}}>ENGINEERING JOURNEY</div><Link href={`${base}/oss/story`} className="group mt-3 inline-flex max-w-full items-center gap-3"><span className="text-2xl font-semibold tracking-[-0.03em] group-hover:text-[var(--accent)] sm:text-3xl" style={{color:'var(--text)'}}>2013 community → Cloud Native → OSS → Teaching</span><ArrowUpRight className="hidden h-5 w-5 shrink-0 sm:block" style={{color:'var(--accent)'}}/></Link><p className="mt-3 max-w-2xl text-sm leading-6" style={{color:'var(--text-muted)'}}>{copy.story}</p></section></main>}
