import Link from 'next/link';
import { ArrowUpRight } from 'lucide-react';
import { getTranslations } from 'next-intl/server';
import { routing } from '@/i18n/routing';
import { communityActivities, awards, researchReports, expertActivities } from '@/lib/data/about';

export function generateStaticParams(){return routing.locales.map(locale=>({locale}))}
export async function generateMetadata({params}:{params:Promise<{locale:string}>}){const{locale}=await params;const t=await getTranslations({locale,namespace:'about'});return{title:t('title'),description:locale==='en'?'Open Engineering Lab — engineering practice, public work, teaching and community evidence.':'Open Engineering Lab — 엔지니어링 실천, 공개 활동, 교육과 커뮤니티 evidence.'}}

export default async function AboutPage({params}:{params:Promise<{locale:string}>}){
  const{locale}=await params;const en=locale==='en';const base=en?'/en':'/ko';const sortedAwards=[...awards].sort((a,b)=>b.year-a.year);const advisory=[...expertActivities].sort((a,b)=>b.year-a.year)[0];
  const roles=en?[['2013','Cloud & DevOps Engineer','Present','K-PaaS Lite · Kubernetes platform engineering · OSS development'],['2015','Community Leader','Present','CloudBro AI · OPA · OPDC'],['2026','Adjunct Professor · Tech University of Korea','Present','Teaching software framework engineering']]:[['2013','Cloud & DevOps Engineer','현재','K-PaaS Lite · Kubernetes platform engineering · OSS development'],['2015','Community Leader','현재','CloudBro AI · OPA · OPDC'],['2026','겸임교수 · 한국공학대학교','현재','SW 프레임워크 엔지니어링 강의']];
  const philosophy=en?[['01','Define the problem first.','A tool is not the goal; a constraint worth solving is.'],['02','Verify what survives integration.','Claims become useful only when someone can inspect or repeat the evidence.'],['03','Use AI for acceleration, not authority.','Exploration and implementation can be accelerated; judgement and verification stay human.']]:[['01','문제를 먼저 정의한다.','도구가 목표가 아니라 해결할 가치가 있는 제약이 출발점입니다.'],['02','통합을 통과한 것을 검증한다.','주장은 누군가 확인하거나 반복할 수 있는 evidence가 있을 때 의미가 생깁니다.'],['03','AI는 가속기로 사용한다.','탐색과 구현은 가속할 수 있지만 판단과 검증은 직접 합니다.']];
  const paths=en?[['Work','Inspect systems, architecture and development pulse.','/projects'],['Story','See how engineering judgement changed over time.','/oss/story'],['Knowledge','Trace notes, docs and talks back to their source systems.','/knowledge']]:[['Work','시스템·아키텍처·개발 흐름을 확인합니다.','/projects'],['Story','엔지니어링 판단이 어떻게 변해왔는지 봅니다.','/oss/story'],['Knowledge','노트·문서·발표를 원 시스템까지 추적합니다.','/knowledge']];
  return <main>
    <section className="border-b" style={{borderColor:'var(--border)'}}><div className="mx-auto max-w-[1440px] px-5 py-14 sm:px-8 lg:px-16 lg:py-20"><div className="font-mono text-xs font-semibold tracking-[0.14em]" style={{color:'var(--accent)'}}>ABOUT / PRACTICE OVER TIME</div><h1 className="mt-5 max-w-5xl text-4xl font-semibold tracking-[-0.055em] sm:text-6xl" style={{color:'var(--text)'}}>{en?<>Build in public.<br/>Keep the evidence.</>:<>공개적으로 만들고,<br/>검증 근거를 남깁니다.</>}</h1><p className="mt-6 max-w-4xl text-base leading-8 sm:text-lg" style={{color:'var(--text-muted)'}}>{en?'This is a practice record: roles, public work, recognition, research and the operating principles behind the engineering observatory.':'이 페이지는 이력 카드 모음이 아니라 역할·공개 활동·수상·연구와 Engineering Observatory를 운영하는 원칙을 시간축으로 보여주는 practice record입니다.'}</p></div></section>

    <section className="border-b" style={{borderColor:'var(--border)',backgroundColor:'var(--surface-hi)'}}><div className="mx-auto max-w-[1440px] px-5 py-5 sm:px-8 lg:px-16"><div className="flex flex-wrap gap-x-7 gap-y-2 font-mono text-[9px] uppercase tracking-[0.1em]" style={{color:'var(--text-faint)'}}><span style={{color:'var(--accent)'}}>01 / Roles</span><span>02 / Public work</span><span>03 / Recognition</span><span>04 / Research</span><span>05 / Principles</span><span>06 / Continue</span></div></div></section>

    <section className="mx-auto max-w-[1440px] px-5 py-12 sm:px-8 lg:px-16"><div className="grid gap-10 lg:grid-cols-[260px_1fr]"><div><div className="font-mono text-[10px] font-semibold tracking-[0.13em]" style={{color:'var(--accent)'}}>01 / CURRENT ROLES</div><h2 className="mt-3 text-3xl font-semibold tracking-[-0.04em]" style={{color:'var(--text)'}}>{en?'Practice that compounds over time':'시간에 따라 쌓이는 실천'}</h2><p className="mt-3 text-sm leading-6" style={{color:'var(--text-muted)'}}>{en?'Engineering, community and teaching are shown on one timeline because they feed the same practice.':'엔지니어링·커뮤니티·교육을 따로 떼지 않고 하나의 practice timeline으로 봅니다.'}</p></div><div className="relative border-l pl-7" style={{borderColor:'var(--border-strong)'}}>{roles.map(([start,title,end,description])=><div key={title} className="relative pb-8 last:pb-0"><span className="absolute -left-[32px] top-1 h-2.5 w-2.5 rounded-full" style={{backgroundColor:'var(--accent)'}}/><div className="font-mono text-[10px]" style={{color:'var(--accent)'}}>{start} → {end}</div><div className="mt-2 text-xl font-semibold" style={{color:'var(--text)'}}>{title}</div><p className="mt-2 text-sm leading-6" style={{color:'var(--text-muted)'}}>{description}</p></div>)}</div></div></section>

    <section className="border-y" style={{borderColor:'var(--border)',backgroundColor:'var(--surface-hi)'}}><div className="mx-auto grid max-w-[1440px] gap-10 px-5 py-12 sm:px-8 lg:grid-cols-2 lg:px-16"><div><div className="font-mono text-[10px] font-semibold tracking-[0.13em]" style={{color:'var(--signal)'}}>02 / PUBLIC WORK</div><h2 className="mt-3 text-3xl font-semibold tracking-[-0.04em]" style={{color:'var(--text)'}}>{en?'Community over time':'시간으로 증명되는 커뮤니티 활동'}</h2><div className="mt-6 divide-y" style={{borderColor:'var(--border)'}}>{communityActivities.slice(0,5).map(item=><div key={item.org} className="py-4 first:pt-0"><div className="flex flex-wrap items-baseline justify-between gap-2"><div className="font-semibold" style={{color:'var(--text)'}}>{item.org} · {item.role}</div><div className="font-mono text-[9px]" style={{color:'var(--accent)'}}>{item.period}</div></div><p className="mt-2 text-sm leading-6" style={{color:'var(--text-muted)'}}>{item.desc}</p></div>)}</div></div><div><div className="font-mono text-[10px] font-semibold tracking-[0.13em]" style={{color:'var(--accent)'}}>03 / RECOGNITION</div><h2 className="mt-3 text-3xl font-semibold tracking-[-0.04em]" style={{color:'var(--text)'}}>Recognition & awards</h2><div className="mt-6 divide-y" style={{borderColor:'var(--border)'}}>{sortedAwards.slice(0,7).map(item=><div key={`${item.year}-${item.title}`} className="grid grid-cols-[70px_1fr] gap-4 py-4 first:pt-0"><div className="font-mono text-xs" style={{color:'var(--text-faint)'}}>{item.year}</div><div className={item.highlight?'font-semibold':''} style={{color:item.highlight?'var(--accent)':'var(--text)'}}>{item.title}</div></div>)}</div></div></div></section>

    <section className="mx-auto max-w-[1440px] px-5 py-12 sm:px-8 lg:px-16"><div className="grid gap-10 lg:grid-cols-[.7fr_1.3fr]"><div><div className="font-mono text-[10px] font-semibold tracking-[0.13em]" style={{color:'var(--accent-2)'}}>04 / RESEARCH / ADVISORY</div><h2 className="mt-3 text-3xl font-semibold tracking-[-0.04em]" style={{color:'var(--text)'}}>{en?'Practice feeds research. Research feeds practice.':'실천과 연구를 다시 연결합니다.'}</h2></div><div className="divide-y" style={{borderColor:'var(--border)'}}>{advisory&&<div className="py-4 first:pt-0"><div className="font-mono text-[9px]" style={{color:'var(--accent)'}}>{advisory.year} / ADVISORY</div><div className="mt-2 text-lg font-semibold" style={{color:'var(--text)'}}>{advisory.title}</div></div>}{researchReports.slice(0,4).map(item=><div key={`${item.year}-${item.title}`} className="py-4"><div className="font-mono text-[9px]" style={{color:'var(--text-faint)'}}>{item.year} / REPORT</div><div className="mt-2 text-lg font-semibold" style={{color:'var(--text)'}}>{item.title}</div></div>)}</div></div></section>

    <section className="border-y" style={{borderColor:'var(--border)',backgroundColor:'var(--surface-hi)'}}><div className="mx-auto max-w-[1440px] px-5 py-12 sm:px-8 lg:px-16"><div className="font-mono text-[10px] font-semibold tracking-[0.13em]" style={{color:'var(--signal)'}}>05 / OPERATING PRINCIPLES</div><h2 className="mt-3 text-3xl font-semibold tracking-[-0.04em]" style={{color:'var(--text)'}}>Build → Verify → Learn → Share</h2><div className="mt-7 grid gap-6 lg:grid-cols-3">{philosophy.map(([index,title,description])=><div key={index} className="border-l pl-5" style={{borderColor:'var(--border-strong)'}}><div className="font-mono text-[10px]" style={{color:'var(--accent)'}}>{index}</div><div className="mt-3 text-xl font-semibold" style={{color:'var(--text)'}}>{title}</div><p className="mt-3 text-sm leading-6" style={{color:'var(--text-muted)'}}>{description}</p></div>)}</div></div></section>

    <section className="mx-auto max-w-[1440px] px-5 py-12 sm:px-8 lg:px-16"><div className="font-mono text-[10px] font-semibold tracking-[0.13em]" style={{color:'var(--accent)'}}>06 / CONTINUE THROUGH THE OBSERVATORY</div><div className="mt-7 divide-y" style={{borderColor:'var(--border)'}}>{paths.map(([title,description,href])=><Link key={title} href={`${base}${href}`} className="group grid gap-3 py-6 first:pt-0 md:grid-cols-[180px_1fr_auto] md:items-start"><div className="text-xl font-semibold group-hover:text-[var(--accent)]" style={{color:'var(--text)'}}>{title}</div><p className="text-sm leading-6" style={{color:'var(--text-muted)'}}>{description}</p><ArrowUpRight className="h-4 w-4" style={{color:'var(--text-faint)'}}/></Link>)}</div></section>
  </main>
}
