import { getTranslations } from 'next-intl/server';
import { routing } from '@/i18n/routing';
import { communityActivities, awards, researchReports, expertActivities } from '@/lib/data/about';

export function generateStaticParams(){return routing.locales.map(locale=>({locale}))}
export async function generateMetadata({params}:{params:Promise<{locale:string}>}){const{locale}=await params;const t=await getTranslations({locale,namespace:'about'});return{title:t('title'),description:locale==='en'?'Open Engineering Lab — engineering practice, public work, teaching and community evidence.':'Open Engineering Lab — 엔지니어링 실천, 공개 활동, 교육과 커뮤니티 evidence.'}}

export default async function AboutPage({params}:{params:Promise<{locale:string}>}){
  const{locale}=await params;const en=locale==='en';const sortedAwards=[...awards].sort((a,b)=>b.year-a.year);const advisory=[...expertActivities].sort((a,b)=>b.year-a.year)[0];
  const roles=en?[['Cloud & DevOps Engineer','2013 — Present','K-PaaS Lite · Kubernetes platform engineering · OSS development'],['Adjunct Professor · Tech University of Korea','2026 — Present','Teaching software framework engineering'],['Community Leader','2015 — Present','CloudBro AI · OPA · OPDC']]:[['Cloud & DevOps Engineer','2013 — 현재','K-PaaS Lite · Kubernetes platform engineering · OSS development'],['겸임교수 · 한국공학대학교','2026 — 현재','SW 프레임워크 엔지니어링 강의'],['Community Leader','2015 — 현재','CloudBro AI · OPA · OPDC']];
  const philosophy=en?[['01','Define the problem first.','A tool is not the goal; a constraint worth solving is.'],['02','Verify what survives integration.','Claims become useful only when someone can inspect or repeat the evidence.'],['03','Use AI for acceleration, not authority.','Exploration and implementation can be accelerated; judgement and verification stay human.']]:[['01','문제를 먼저 정의한다.','도구가 목표가 아니라 해결할 가치가 있는 제약이 출발점입니다.'],['02','통합을 통과한 것을 검증한다.','주장은 누군가 확인하거나 반복할 수 있는 evidence가 있을 때 의미가 생깁니다.'],['03','AI는 가속기로 사용한다.','탐색과 구현은 가속할 수 있지만 판단과 검증은 직접 합니다.']];
  return <main>
    <section className="border-b" style={{borderColor:'var(--border)'}}><div className="mx-auto max-w-[1440px] px-5 py-14 sm:px-8 lg:px-16 lg:py-20"><div className="font-mono text-xs font-semibold tracking-[0.14em]" style={{color:'var(--accent)'}}>ABOUT / ENGINEERING PRACTICE</div><h1 className="mt-5 max-w-5xl text-4xl font-semibold tracking-[-0.055em] sm:text-6xl" style={{color:'var(--text)'}}>{en?<>Build in public.<br/>Keep the evidence.</>:<>공개적으로 만들고,<br/>검증 근거를 남깁니다.</>}</h1><p className="mt-6 max-w-4xl text-base leading-8 sm:text-lg" style={{color:'var(--text-muted)'}}>{en?'This page is not a biography card wall. It shows the roles, public work and operating principles that explain how the engineering lab is run.':'이 페이지는 이력 카드 모음이 아니라 Open Engineering Lab을 어떤 역할과 원칙으로 운영하는지 보여주는 evidence page입니다.'}</p></div></section>

    <section className="mx-auto max-w-[1440px] px-5 py-12 sm:px-8 lg:px-16"><div className="font-mono text-[10px] font-semibold tracking-[0.13em]" style={{color:'var(--accent)'}}>CURRENT ROLES</div><div className="mt-6 divide-y" style={{borderColor:'var(--border)'}}>{roles.map(([title,meta,description],i)=><div key={title} className="grid gap-3 py-6 first:pt-0 lg:grid-cols-[64px_1.1fr_.6fr_1.3fr]"><div className="font-mono text-[10px]" style={{color:'var(--text-faint)'}}>0{i+1}</div><div className="text-xl font-semibold" style={{color:'var(--text)'}}>{title}</div><div className="font-mono text-[10px]" style={{color:'var(--accent)'}}>{meta}</div><p className="text-sm leading-6" style={{color:'var(--text-muted)'}}>{description}</p></div>)}</div></section>

    <section className="border-y" style={{borderColor:'var(--border)',backgroundColor:'var(--surface-hi)'}}><div className="mx-auto grid max-w-[1440px] gap-10 px-5 py-12 sm:px-8 lg:grid-cols-2 lg:px-16"><div><div className="font-mono text-[10px] font-semibold tracking-[0.13em]" style={{color:'var(--signal)'}}>PUBLIC WORK</div><h2 className="mt-3 text-3xl font-semibold tracking-[-0.04em]" style={{color:'var(--text)'}}>{en?'Community over time':'시간으로 증명되는 커뮤니티 활동'}</h2><div className="mt-6 divide-y" style={{borderColor:'var(--border)'}}>{communityActivities.slice(0,4).map(item=><div key={item.org} className="py-4 first:pt-0"><div className="flex flex-wrap items-baseline justify-between gap-2"><div className="font-semibold" style={{color:'var(--text)'}}>{item.org} · {item.role}</div><div className="font-mono text-[9px]" style={{color:'var(--accent)'}}>{item.period}</div></div><p className="mt-2 text-sm leading-6" style={{color:'var(--text-muted)'}}>{item.desc}</p></div>)}</div></div><div><div className="font-mono text-[10px] font-semibold tracking-[0.13em]" style={{color:'var(--accent)'}}>RECOGNITION</div><h2 className="mt-3 text-3xl font-semibold tracking-[-0.04em]" style={{color:'var(--text)'}}>Recognition & awards</h2><div className="mt-6 divide-y" style={{borderColor:'var(--border)'}}>{sortedAwards.slice(0,6).map(item=><div key={`${item.year}-${item.title}`} className="grid grid-cols-[70px_1fr] gap-4 py-4 first:pt-0"><div className="font-mono text-xs" style={{color:'var(--text-faint)'}}>{item.year}</div><div className={item.highlight?'font-semibold':''} style={{color:item.highlight?'var(--accent)':'var(--text)'}}>{item.title}</div></div>)}</div></div></div></section>

    <section className="mx-auto max-w-[1440px] px-5 py-12 sm:px-8 lg:px-16"><div className="grid gap-10 lg:grid-cols-[.7fr_1.3fr]"><div><div className="font-mono text-[10px] font-semibold tracking-[0.13em]" style={{color:'var(--accent-2)'}}>RESEARCH / ADVISORY</div><h2 className="mt-3 text-3xl font-semibold tracking-[-0.04em]" style={{color:'var(--text)'}}>{en?'Practice feeds research. Research feeds practice.':'실천과 연구를 다시 연결합니다.'}</h2></div><div className="divide-y" style={{borderColor:'var(--border)'}}>{advisory&&<div className="py-4 first:pt-0"><div className="font-mono text-[9px]" style={{color:'var(--accent)'}}>{advisory.year}</div><div className="mt-2 text-lg font-semibold" style={{color:'var(--text)'}}>{advisory.title}</div></div>}{researchReports.slice(0,3).map(item=><div key={`${item.year}-${item.title}`} className="py-4"><div className="font-mono text-[9px]" style={{color:'var(--text-faint)'}}>{item.year}</div><div className="mt-2 text-lg font-semibold" style={{color:'var(--text)'}}>{item.title}</div></div>)}</div></div></section>

    <section className="border-y" style={{borderColor:'var(--border)',backgroundColor:'var(--surface-hi)'}}><div className="mx-auto max-w-[1440px] px-5 py-12 sm:px-8 lg:px-16"><div className="font-mono text-[10px] font-semibold tracking-[0.13em]" style={{color:'var(--signal)'}}>OPERATING PRINCIPLES</div><h2 className="mt-3 text-3xl font-semibold tracking-[-0.04em]" style={{color:'var(--text)'}}>Build → Verify → Learn → Share</h2><div className="mt-7 grid gap-6 lg:grid-cols-3">{philosophy.map(([index,title,description])=><div key={index} className="border-l pl-5" style={{borderColor:'var(--border-strong)'}}><div className="font-mono text-[10px]" style={{color:'var(--accent)'}}>{index}</div><div className="mt-3 text-xl font-semibold" style={{color:'var(--text)'}}>{title}</div><p className="mt-3 text-sm leading-6" style={{color:'var(--text-muted)'}}>{description}</p></div>)}</div></div></section>
  </main>
}
