import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import Link from 'next/link';
import { ArrowLeft, ArrowUpRight } from 'lucide-react';
import { getPostBySlug, getPosts, getProjects } from '@/lib/content';
import { MDXContent } from '@/components/MDXContent';
import { routing } from '@/i18n/routing';
import readingTime from 'reading-time';

export function generateStaticParams(){const params:{locale:string;slug:string}[]=[];routing.locales.forEach(locale=>{const lang=locale as 'ko'|'en';getPosts(lang).forEach(post=>params.push({locale,slug:post.slug}))});return params}
export async function generateMetadata({params}:{params:Promise<{locale:string;slug:string}>}):Promise<Metadata>{const{locale,slug}=await params;const lang=locale as 'ko'|'en';const result=getPostBySlug(slug,lang);if(!result)return{};const{meta}=result;const url=`https://cne.io.kr/${lang}/posts/${slug}`;const image=meta.image??'/images/notes-cover.svg';return{title:meta.title,description:meta.description,alternates:{canonical:url},openGraph:{type:'article',url,title:meta.title,description:meta.description,publishedTime:meta.pubDate,modifiedTime:meta.updatedDate,tags:meta.tags,images:[{url:image,alt:`${meta.title} cover`}]}}}

export default async function PostPage({params}:{params:Promise<{locale:string;slug:string}>}){const{locale,slug}=await params;const lang=locale as 'ko'|'en';const result=getPostBySlug(slug,lang);if(!result)notFound();const{meta,content}=result;const base=lang==='en'?'/en':'/ko';const digest=slug.startsWith('daily-digest-');const read=readingTime(content);const projects=getProjects(lang);const explicit=projects.filter(project=>meta.projects?.includes(project.slug));const related=explicit.length>0?explicit:projects.filter(project=>{const terms=[project.slug,project.title,...project.tags].map(value=>value.toLowerCase());return meta.tags.some(tag=>terms.includes(tag.toLowerCase()))||meta.title.toLowerCase().includes(project.title.toLowerCase())}).slice(0,3);
return <main>
<div className="mx-auto max-w-[1080px] px-5 pt-8 sm:px-8"><Link href={digest?`${base}/tech-digest`:`${base}/knowledge`} className="inline-flex items-center gap-2 text-sm" style={{color:'var(--text-muted)'}}><ArrowLeft className="h-4 w-4"/>{lang==='en'?'Back to knowledge':'Knowledge로 돌아가기'}</Link></div>
<header className="mx-auto max-w-[1080px] px-5 pb-10 pt-10 sm:px-8 sm:pb-14"><div className="font-mono text-[10px] font-semibold tracking-[0.12em]" style={{color:digest?'var(--signal)':'var(--accent)'}}>{digest?'TECH SIGNAL':'FIELD NOTE'} / {meta.pubDate.slice(0,10)} · {Math.max(1,Math.ceil(read.minutes))} MIN</div><h1 className="mt-5 max-w-4xl text-4xl font-semibold tracking-[-0.055em] sm:text-6xl sm:leading-[1.05]" style={{color:'var(--text)'}}>{meta.title}</h1>{meta.description&&<p className="mt-6 max-w-3xl text-lg leading-8" style={{color:'var(--text-muted)'}}>{meta.description}</p>}<div className="mt-6 font-mono text-[9px] uppercase leading-6 tracking-[0.09em]" style={{color:'var(--text-faint)'}}>{meta.tags.join(' · ')}</div></header>

{related.length>0&&<section className="border-y" style={{borderColor:'var(--border)',backgroundColor:'var(--surface-hi)'}}><div className="mx-auto max-w-[1080px] px-5 py-7 sm:px-8"><div className="grid gap-4 sm:grid-cols-[180px_1fr]"><div><div className="font-mono text-[10px] font-semibold tracking-[0.12em]" style={{color:'var(--signal)'}}>PROVENANCE</div><p className="mt-2 text-xs leading-5" style={{color:'var(--text-muted)'}}>{lang==='en'?'Systems that give this note context.':'이 글의 맥락이 된 시스템.'}</p></div><div className="divide-y" style={{borderColor:'var(--border)'}}>{related.map(project=><Link key={project.slug} href={`${base}/projects/${project.slug}`} className="group flex items-center justify-between gap-4 py-3 first:pt-0 last:pb-0"><div><div className="text-sm font-semibold group-hover:text-[var(--accent)]" style={{color:'var(--text)'}}>{project.title}</div><div className="mt-1 font-mono text-[9px] uppercase tracking-[0.08em]" style={{color:'var(--text-faint)'}}>{project.tags.slice(0,3).join(' · ')}</div></div><ArrowUpRight className="h-3.5 w-3.5" style={{color:'var(--text-faint)'}}/></Link>)}</div></div></div></section>}

<section className="mx-auto grid max-w-[1080px] gap-10 px-5 py-12 sm:px-8 lg:grid-cols-[180px_1fr]"><aside className="hidden lg:block"><div className="sticky top-24"><div className="font-mono text-[9px] font-semibold tracking-[0.12em]" style={{color:'var(--accent)'}}>ENGINEERING REPORT</div><div className="mt-5 space-y-4 font-mono text-[9px] uppercase tracking-[0.08em]" style={{color:'var(--text-faint)'}}><div>01 / Context</div><div>02 / Decision</div><div>03 / Evidence</div><div>04 / Lessons</div></div></div></aside><article className="cne-doc-prose prose prose-lg min-w-0 max-w-[820px] prose-headings:font-semibold"><MDXContent source={content}/></article></section>

<section className="border-t" style={{borderColor:'var(--border)',backgroundColor:'var(--surface-hi)'}}><div className="mx-auto max-w-[1080px] px-5 py-9 sm:px-8"><div className="grid gap-5 sm:grid-cols-[1fr_auto] sm:items-end"><div><div className="font-mono text-[10px] font-semibold tracking-[0.12em]" style={{color:'var(--accent)'}}>NEXT PATH</div><h2 className="mt-2 text-2xl font-semibold tracking-[-0.035em]" style={{color:'var(--text)'}}>{lang==='en'?'Follow the lesson back into the system.':'교훈을 다시 시스템 안에서 확인합니다.'}</h2></div><Link href={related[0]?`${base}/projects/${related[0].slug}`:`${base}/knowledge`} className="inline-flex items-center gap-2 text-sm font-semibold" style={{color:'var(--accent)'}}>{related[0]?related[0].title:(lang==='en'?'Knowledge hub':'Knowledge 허브')} <ArrowUpRight className="h-4 w-4"/></Link></div></div></section>
</main>}
