import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import Link from 'next/link';
import { ArrowLeft, ArrowUpRight } from 'lucide-react';
import { getPostBySlug, getPosts, getProjects } from '@/lib/content';
import { MDXContent } from '@/components/MDXContent';
import { routing } from '@/i18n/routing';
import readingTime from 'reading-time';

export function generateStaticParams(){const params:{locale:string;slug:string}[]=[];routing.locales.forEach(locale=>{const lang=locale as 'ko'|'en';getPosts(lang).forEach(post=>params.push({locale,slug:post.slug}))});return params}
export async function generateMetadata({params}:{params:Promise<{locale:string;slug:string}>}):Promise<Metadata>{const{locale,slug}=await params;const lang=locale as 'ko'|'en';const result=getPostBySlug(slug,lang);if(!result)return{};const{meta}=result;const url=`https://cne.io.kr/${lang}/posts/${slug}`;const image=meta.image??'/images/notes-cover.svg';return{title:meta.title,description:meta.description,alternates:{canonical:url},openGraph:{type:'article',url,title:meta.title,description:meta.description,publishedTime:meta.pubDate,modifiedTime:meta.updatedDate,tags:meta.tags,images:[{url:image,alt:`${meta.title} cover`}]}}}

export default async function PostPage({params}:{params:Promise<{locale:string;slug:string}>}){const{locale,slug}=await params;const lang=locale as 'ko'|'en';const result=getPostBySlug(slug,lang);if(!result)notFound();const{meta,content}=result;const base=lang==='en'?'/en':'/ko';const digest=slug.startsWith('daily-digest-');const read=readingTime(content);const projects=getProjects(lang);const explicit=projects.filter(project=>meta.projects?.includes(project.slug));const related=explicit.length>0?explicit:projects.filter(project=>{const terms=[project.slug,project.title,...project.tags].map(value=>value.toLowerCase());return meta.tags.some(tag=>terms.includes(tag.toLowerCase()))||meta.title.toLowerCase().includes(project.title.toLowerCase())}).slice(0,3);const minutes=Math.max(1,Math.ceil(read.minutes));
return <main>
<div className="mx-auto max-w-[1080px] px-5 pt-8 sm:px-8"><Link href={digest?`${base}/tech-digest`:`${base}/knowledge`} className="inline-flex items-center gap-2 text-sm" style={{color:'var(--text-muted)'}}><ArrowLeft className="h-4 w-4"/>{lang==='en'?'Back to knowledge':'Knowledge로 돌아가기'}</Link></div>
<header className="mx-auto max-w-[1080px] px-5 pb-8 pt-10 sm:px-8"><div className="font-mono text-[10px] font-semibold tracking-[0.12em]" style={{color:digest?'var(--signal)':'var(--accent)'}}>{digest?'TECH SIGNAL':'FIELD NOTE'} / ENGINEERING REPORT</div><h1 className="mt-5 max-w-4xl text-4xl font-semibold tracking-[-0.055em] sm:text-6xl sm:leading-[1.05]" style={{color:'var(--text)'}}>{meta.title}</h1>{meta.description&&<p className="mt-6 max-w-3xl text-lg leading-8" style={{color:'var(--text-muted)'}}>{meta.description}</p>}<div className="mt-6 font-mono text-[9px] uppercase leading-6 tracking-[0.09em]" style={{color:'var(--text-faint)'}}>{meta.tags.join(' · ')}</div></header>
<section className="border-y" style={{borderColor:'var(--border)',backgroundColor:'var(--surface-hi)'}}><div className="mx-auto grid max-w-[1080px] grid-cols-2 gap-x-8 gap-y-5 px-5 py-5 sm:grid-cols-4 sm:px-8"><ReportMeta label={lang==='en'?'Published':'게시일'} value={meta.pubDate.slice(0,10)}/><ReportMeta label={lang==='en'?'Reading time':'읽기 시간'} value={`${minutes} min`}/><ReportMeta label={lang==='en'?'Source systems':'연결 시스템'} value={related.length?String(related.length):'—'}/><ReportMeta label={lang==='en'?'Record type':'기록 유형'} value={digest?'Signal':'Field note'}/></div></section>

{related.length>0&&<section><div className="mx-auto max-w-[1080px] px-5 py-8 sm:px-8"><div className="grid gap-4 sm:grid-cols-[180px_1fr]"><div><div className="font-mono text-[10px] font-semibold tracking-[0.12em]" style={{color:'var(--signal)'}}>PROVENANCE</div><p className="mt-2 text-xs leading-5" style={{color:'var(--text-muted)'}}>{lang==='en'?'Trace the lesson back to the systems that created the context.':'이 교훈이 필요했던 시스템으로 다시 추적합니다.'}</p></div><div className="divide-y" style={{borderColor:'var(--border)'}}>{related.map(project=><Link key={project.slug} href={`${base}/projects/${project.slug}`} className="group flex items-center justify-between gap-4 py-3 first:pt-0 last:pb-0"><div><div className="text-sm font-semibold group-hover:text-[var(--accent)]" style={{color:'var(--text)'}}>{project.title}</div><div className="mt-1 font-mono text-[9px] uppercase tracking-[0.08em]" style={{color:'var(--text-faint)'}}>{project.tags.slice(0,3).join(' · ')}</div></div><ArrowUpRight className="h-3.5 w-3.5" style={{color:'var(--text-faint)'}}/></Link>)}</div></div></div></section>}

<section className="border-t" style={{borderColor:'var(--border)'}}><div className="mx-auto grid max-w-[1080px] gap-10 px-5 py-12 sm:px-8 lg:grid-cols-[180px_1fr]"><aside className="hidden lg:block"><div className="sticky top-24"><div className="font-mono text-[9px] font-semibold tracking-[0.12em]" style={{color:'var(--accent)'}}>REPORT LENS</div><div className="mt-5 space-y-4 font-mono text-[9px] uppercase tracking-[0.08em]" style={{color:'var(--text-faint)'}}><div>01 / Context</div><div>02 / Decision</div><div>03 / Evidence</div><div>04 / Lessons</div><div className="pt-3" style={{color:'var(--signal)'}}>→ Source system</div></div></div></aside><article className="cne-doc-prose prose prose-lg min-w-0 max-w-[820px] prose-headings:font-semibold"><MDXContent source={content}/></article></div></section>

<section className="border-t" style={{borderColor:'var(--border)',backgroundColor:'var(--surface-hi)'}}><div className="mx-auto max-w-[1080px] px-5 py-10 sm:px-8"><div className="grid gap-5 sm:grid-cols-[1fr_auto] sm:items-end"><div><div className="font-mono text-[10px] font-semibold tracking-[0.12em]" style={{color:'var(--accent)'}}>NEXT PATH / VERIFY IN CONTEXT</div><h2 className="mt-2 text-2xl font-semibold tracking-[-0.035em]" style={{color:'var(--text)'}}>{lang==='en'?'Follow the lesson back into the system.':'교훈을 다시 시스템 안에서 확인합니다.'}</h2><p className="mt-2 max-w-2xl text-sm leading-6" style={{color:'var(--text-muted)'}}>{lang==='en'?'The article is one observation. The project record holds architecture, development pulse, proof and the wider engineering context.':'글은 하나의 관찰 기록이고, 프로젝트 상세에는 아키텍처·개발 흐름·검증 근거와 더 넓은 맥락이 남습니다.'}</p></div><Link href={related[0]?`${base}/projects/${related[0].slug}`:`${base}/knowledge`} className="inline-flex items-center gap-2 text-sm font-semibold" style={{color:'var(--accent)'}}>{related[0]?related[0].title:(lang==='en'?'Knowledge hub':'Knowledge 허브')} <ArrowUpRight className="h-4 w-4"/></Link></div></div></section>
</main>}

function ReportMeta({label,value}:{label:string;value:string}){return <div><div className="font-mono text-[9px] uppercase tracking-[0.1em]" style={{color:'var(--text-faint)'}}>{label}</div><div className="mt-1 text-sm font-semibold" style={{color:'var(--text)'}}>{value}</div></div>}
