import Link from 'next/link';
import { Rss, ArrowUpRight } from 'lucide-react';
import { getTranslations } from 'next-intl/server';
import { getTechDigests } from '@/lib/content';
import { routing } from '@/i18n/routing';

export function generateStaticParams(){return routing.locales.map(locale=>({locale}))}
export async function generateMetadata({params}:{params:Promise<{locale:string}>}){const{locale}=await params;const t=await getTranslations({locale,namespace:'tech_digest'});return{title:t('title'),description:t('subtitle')}}
const pipeline=['RSS collection','Korean + English digest generation','AI enrichment / validation','Draft PR','Fallback publication when needed','GitHub Pages deployment'] as const;
const guardrails=['Duplicate-publication guards','Fallback handling','Enrichment validation','Explicit separation from original Notes','Bilingual generation'] as const;

export default async function TechDigestPage({params}:{params:Promise<{locale:string}>}){
  const{locale}=await params;const lang=locale as 'ko'|'en';const posts=getTechDigests(lang);const base=lang==='en'?'/en':'/ko';const rss=lang==='en'?'/tech-digest-en.xml':'/tech-digest.xml';
  return <main>
    <section className="border-b" style={{borderColor:'var(--border)'}}><div className="mx-auto max-w-[1440px] px-5 py-12 sm:px-8 lg:px-16 lg:py-16"><div className="flex items-center justify-between gap-4"><div className="font-mono text-xs font-medium tracking-[0.12em]" style={{color:'var(--signal)'}}>TECH SIGNAL / AUTOMATED OBSERVATION</div><Link href={rss} className="inline-flex items-center gap-2 rounded-full border px-3 py-2 font-mono text-[10px]" style={{borderColor:'var(--border)',color:'var(--text-muted)'}}><Rss className="h-3.5 w-3.5"/>RSS</Link></div><h1 className="mt-4 max-w-5xl text-4xl font-semibold tracking-[-0.05em] sm:text-5xl" style={{color:'var(--text)'}}>{lang==='en'?'Keep only the signals worth reading.':'읽을 가치가 있는 신호만 남깁니다.'}</h1><p className="mt-5 max-w-4xl text-base leading-7 sm:text-lg" style={{color:'var(--text-muted)'}}>{lang==='en'?'An automated observation lane, deliberately separated from original Field Notes. Collection, enrichment, validation and fallback are visible parts of the publishing system.':'Original Field Note와 의도적으로 분리한 자동 관측 lane입니다. 수집·보강·검증·fallback 자체도 공개된 publishing system의 일부로 봅니다.'}</p></div></section>
    <section className="border-b" style={{borderColor:'var(--border)',backgroundColor:'var(--surface-hi)'}}><div className="mx-auto grid max-w-[1440px] grid-cols-2 gap-6 px-5 py-5 sm:px-8 md:grid-cols-3 lg:px-16"><Metric label={lang==='en'?'Published signals':'게시 신호'} value={String(posts.length)}/><Metric label={lang==='en'?'Pipeline stages':'파이프라인 단계'} value={String(pipeline.length)}/><Metric label={lang==='en'?'Guardrails':'가드레일'} value={String(guardrails.length)}/></div></section>
    <section className="mx-auto max-w-[1440px] px-5 py-10 sm:px-8 lg:px-16"><div className="grid gap-8 lg:grid-cols-[240px_1fr]"><div><div className="font-mono text-[10px] font-semibold tracking-[0.13em]" style={{color:'var(--signal)'}}>PUBLICATION PIPELINE</div><p className="mt-3 text-sm leading-6" style={{color:'var(--text-muted)'}}>{lang==='en'?'A visible automation chain rather than a black-box feed.':'블랙박스 피드가 아니라 자동화 체인을 그대로 드러냅니다.'}</p></div><div className="divide-y" style={{borderColor:'var(--border)'}}>{pipeline.map((step,index)=><div key={step} className="grid grid-cols-[44px_1fr] gap-3 py-3 first:pt-0"><span className="font-mono text-[10px]" style={{color:'var(--text-faint)'}}>{String(index+1).padStart(2,'0')}</span><span className="text-sm font-semibold" style={{color:'var(--text)'}}>{step}</span></div>)}</div></div></section>
    <section className="border-y" style={{borderColor:'var(--border)',backgroundColor:'var(--surface-hi)'}}><div className="mx-auto max-w-[1440px] px-5 py-10 sm:px-8 lg:px-16"><div className="font-mono text-[10px] font-semibold tracking-[0.13em]" style={{color:'var(--signal)'}}>SIGNAL STREAM / LATEST</div><div className="mt-6 divide-y" style={{borderColor:'var(--border)'}}>{posts.map((post,i)=><Link key={post.slug} href={`${base}/posts/${post.slug}`} className="group grid gap-3 py-5 first:pt-0 md:grid-cols-[44px_140px_1fr_1.1fr_auto]" style={{borderColor:'var(--border)'}}><div className="font-mono text-[9px]" style={{color:'var(--text-faint)'}}>{String(i+1).padStart(2,'0')}</div><div className="font-mono text-[10px]" style={{color:'var(--text-faint)'}}>{post.pubDate.slice(0,10)}</div><div><h2 className="font-semibold group-hover:text-[var(--signal)]" style={{color:'var(--text)'}}>{post.title}</h2><div className="mt-2 font-mono text-[9px]" style={{color:'var(--signal)'}}>{post.tags.slice(0,3).join(' · ')}</div></div><p className="line-clamp-2 text-sm leading-6" style={{color:'var(--text-muted)'}}>{post.description||''}</p><ArrowUpRight className="hidden h-4 w-4 md:block" style={{color:'var(--text-faint)'}}/></Link>)}</div></div></section>
    <section className="mx-auto max-w-[1440px] px-5 py-9 sm:px-8 lg:px-16"><div className="grid gap-6 lg:grid-cols-[240px_1fr]"><div className="font-mono text-[10px] font-semibold tracking-[0.13em]" style={{color:'var(--signal)'}}>QUALITY GUARDRAILS</div><div className="grid gap-x-8 gap-y-2 text-sm sm:grid-cols-2" style={{color:'var(--text-muted)'}}>{guardrails.map((item,i)=><div key={item} className="flex gap-3"><span className="font-mono text-[9px]" style={{color:'var(--text-faint)'}}>{String(i+1).padStart(2,'0')}</span><span>{item}</span></div>)}</div></div></section>
  </main>
}
function Metric({label,value}:{label:string;value:string}){return <div><div className="font-mono text-[9px] uppercase tracking-[0.1em]" style={{color:'var(--text-faint)'}}>{label}</div><div className="mt-1 text-lg font-semibold" style={{color:'var(--text)'}}>{value}</div></div>}
