import Link from 'next/link';
import { ArrowUpRight } from 'lucide-react';
import { routing } from '@/i18n/routing';
import { getNotes } from '@/lib/content';

export function generateStaticParams(){return routing.locales.map(locale=>({locale}))}

const channels = [
  { key:'notes', href:'notes', en:'Field Notes', ko:'필드 노트', descEn:'Architecture decisions, integration findings and troubleshooting from real systems.', descKo:'실제 시스템에서 나온 아키텍처 의사결정, 통합 이슈와 트러블슈팅.' },
  { key:'digest', href:'tech-digest', en:'Tech Digest', ko:'테크 다이제스트', descEn:'External signals filtered through a Cloud Native and platform-engineering lens.', descKo:'Cloud Native와 Platform Engineering 관점으로 선별한 외부 기술 신호.' },
  { key:'talks', href:'seminars', en:'Talks', ko:'발표', descEn:'Ideas that survived enough practice to be shared with a wider audience.', descKo:'실전에서 충분히 검증되어 더 넓게 공유한 발표와 세미나.' },
  { key:'docs', href:'docs', en:'Docs', ko:'문서', descEn:'Operational and implementation documentation for projects and experiments.', descKo:'프로젝트와 실험을 위한 운영·구현 문서.' },
] as const;

export default async function KnowledgePage({params}:{params:Promise<{locale:string}>}){
  const {locale}=await params; const lang=locale as 'ko'|'en'; const base=lang==='en'?'/en':'/ko'; const notes=getNotes(lang).slice(0,8);
  return <main>
    <section className="border-b" style={{borderColor:'var(--border)'}}><div className="mx-auto max-w-[1440px] px-5 py-14 sm:px-8 lg:px-16 lg:py-20"><div className="font-mono text-xs font-semibold tracking-[0.14em]" style={{color:'var(--accent)'}}>KNOWLEDGE / CONNECTED TO THE WORK</div><h1 className="mt-5 max-w-5xl text-4xl font-semibold tracking-[-0.055em] sm:text-6xl" style={{color:'var(--text)'}}>{lang==='en'?<>Knowledge connected to<br/>the systems that produced it.</>:<>지식은 글 목록이 아니라,<br/>그것을 만들어낸 시스템과 연결됩니다.</>}</h1><p className="mt-6 max-w-4xl text-base leading-8 sm:text-lg" style={{color:'var(--text-muted)'}}>{lang==='en'?'Field notes, architecture, troubleshooting, research, talks and documentation are different views of the same engineering practice.':'필드 노트, 아키텍처, 트러블슈팅, 리서치, 발표와 문서는 서로 다른 콘텐츠가 아니라 같은 engineering practice를 다른 각도에서 기록한 결과입니다.'}</p></div></section>
    <section className="mx-auto max-w-[1440px] px-5 py-12 sm:px-8 lg:px-16"><div className="grid gap-4 md:grid-cols-2">{channels.map((c,i)=><Link key={c.key} href={`${base}/${c.href}`} className="group rounded-2xl border p-6 transition-transform hover:-translate-y-0.5" style={{borderColor:'var(--border)',backgroundColor:i===0?'var(--surface-hi)':'var(--surface)'}}><div className="font-mono text-[10px] font-semibold tracking-[0.12em]" style={{color:i===2?'var(--signal)':'var(--accent)'}}>0{i+1} / {c.key.toUpperCase()}</div><div className="mt-4 flex items-center justify-between gap-3"><h2 className="text-2xl font-semibold group-hover:text-[var(--accent)]" style={{color:'var(--text)'}}>{lang==='en'?c.en:c.ko}</h2><ArrowUpRight className="h-4 w-4" style={{color:'var(--text-faint)'}}/></div><p className="mt-3 text-sm leading-6" style={{color:'var(--text-muted)'}}>{lang==='en'?c.descEn:c.descKo}</p></Link>)}</div></section>
    <section className="border-y" style={{borderColor:'var(--border)',backgroundColor:'var(--surface-hi)'}}><div className="mx-auto max-w-[1440px] px-5 py-14 sm:px-8 lg:px-16"><div className="font-mono text-[10px] font-semibold tracking-[0.13em]" style={{color:'var(--accent)'}}>LATEST FIELD NOTES</div><div className="mt-7 divide-y" style={{borderColor:'var(--border)'}}>{notes.map((note,i)=><Link key={note.slug} href={`${base}/posts/${note.slug}`} className="group grid gap-2 py-6 first:pt-0 md:grid-cols-[80px_1fr_1.2fr_auto] md:items-start" style={{borderColor:'var(--border)'}}><div className="font-mono text-[10px]" style={{color:'var(--text-faint)'}}>{String(i+1).padStart(2,'0')}</div><div className="text-xl font-semibold group-hover:text-[var(--accent)]" style={{color:'var(--text)'}}>{note.title}</div><p className="text-sm leading-6" style={{color:'var(--text-muted)'}}>{note.description|| (lang==='en'?'Engineering note from the workbench.':'Workbench에서 나온 engineering note.')}</p><ArrowUpRight className="hidden h-4 w-4 md:block" style={{color:'var(--text-faint)'}}/></Link>)}</div></div></section>
    <section className="mx-auto max-w-[1440px] px-5 py-14 sm:px-8 lg:px-16"><div className="grid gap-6 lg:grid-cols-[.7fr_1.3fr]"><div><div className="font-mono text-[10px] font-semibold tracking-[0.13em]" style={{color:'var(--signal)'}}>CROSS-LINKING PRINCIPLE</div><h2 className="mt-3 text-3xl font-semibold tracking-[-0.04em]" style={{color:'var(--text)'}}>{lang==='en'?'Read knowledge in context.':'지식은 맥락과 함께 읽습니다.'}</h2></div><p className="text-base leading-8" style={{color:'var(--text-muted)'}}>{lang==='en'?'A project page should lead to the notes, talks and docs produced by that system; a note should lead back to the project and architecture that made the lesson necessary. The goal is not a bigger archive, but a navigable engineering knowledge graph.':'프로젝트 페이지에서는 그 시스템에서 나온 노트·발표·문서로 이어지고, 노트에서는 다시 그 교훈이 필요했던 프로젝트와 아키텍처로 돌아갈 수 있어야 합니다. 목표는 더 큰 아카이브가 아니라 탐색 가능한 engineering knowledge graph입니다.'}</p></div></section>
  </main>
}
