import Link from 'next/link';
import { ArrowUpRight } from 'lucide-react';
import { routing } from '@/i18n/routing';
import { getNotes, getProjects } from '@/lib/content';

export function generateStaticParams(){return routing.locales.map(locale=>({locale}))}

const channels=[
  {key:'notes',href:'notes',en:'Field Notes',ko:'필드 노트',role:'DECISIONS / INCIDENTS'},
  {key:'digest',href:'tech-digest',en:'Tech Digest',ko:'테크 다이제스트',role:'EXTERNAL SIGNALS'},
  {key:'talks',href:'seminars',en:'Talks',ko:'발표',role:'SHARED PRACTICE'},
  {key:'docs',href:'docs',en:'Docs',ko:'문서',role:'OPERATING KNOWLEDGE'},
] as const;

export default async function KnowledgePage({params}:{params:Promise<{locale:string}>}){
  const{locale}=await params;const lang=locale as 'ko'|'en';const base=lang==='en'?'/en':'/ko';const notes=getNotes(lang).slice(0,12);const projects=getProjects(lang);
  const linked=projects.map(project=>({project,count:notes.filter(note=>note.projects?.includes(project.slug)).length})).filter(item=>item.count>0).sort((a,b)=>b.count-a.count).slice(0,8);
  return <main>
    <section className="border-b" style={{borderColor:'var(--border)'}}><div className="mx-auto max-w-[1440px] px-5 py-14 sm:px-8 lg:px-16 lg:py-20"><div className="font-mono text-xs font-semibold tracking-[0.14em]" style={{color:'var(--accent)'}}>KNOWLEDGE / PROVENANCE STREAM</div><h1 className="mt-5 max-w-5xl text-4xl font-semibold tracking-[-0.055em] sm:text-6xl" style={{color:'var(--text)'}}>{lang==='en'?<>Every article<br/>has a source.</>:<>모든 글에는<br/>출처가 있습니다.</>}</h1><p className="mt-6 max-w-4xl text-base leading-8 sm:text-lg" style={{color:'var(--text-muted)'}}>{lang==='en'?'The primary question is not “which category is this?” but “which system, decision, incident or external signal made this knowledge necessary?”':'먼저 카테고리를 묻기보다 어떤 시스템·의사결정·Incident·외부 신호가 이 지식을 필요하게 만들었는지 보여줍니다.'}</p></div></section>

    <section className="mx-auto grid max-w-[1440px] gap-12 px-5 py-12 sm:px-8 lg:grid-cols-[.62fr_1.38fr] lg:px-16">
      <div><div className="font-mono text-[10px] font-semibold tracking-[0.13em]" style={{color:'var(--signal)'}}>SOURCE SYSTEMS</div><h2 className="mt-3 text-3xl font-semibold tracking-[-0.04em]" style={{color:'var(--text)'}}>{lang==='en'?'Start from the system.':'시스템에서 시작합니다.'}</h2><p className="mt-4 text-sm leading-6" style={{color:'var(--text-muted)'}}>{lang==='en'?'Systems with more linked notes surface naturally, but the count is context — not a ranking.':'연결된 노트가 많은 시스템은 자연스럽게 드러나지만, 숫자는 순위가 아니라 맥락입니다.'}</p></div>
      <div className="divide-y" style={{borderColor:'var(--border)'}}>{linked.length>0?linked.map(({project,count})=><Link key={project.slug} href={`${base}/projects/${project.slug}`} className="group grid grid-cols-[1fr_auto] gap-5 py-5 first:pt-0"><div><div className="text-xl font-semibold group-hover:text-[var(--accent)]" style={{color:'var(--text)'}}>{project.title}</div><div className="mt-1 font-mono text-[9px] uppercase tracking-[0.08em]" style={{color:'var(--text-faint)'}}>{project.tags.slice(0,3).join(' · ')}</div></div><div className="text-right"><div className="text-2xl font-semibold" style={{color:'var(--accent)'}}>{count}</div><div className="font-mono text-[9px]" style={{color:'var(--text-faint)'}}>LINKED NOTES</div></div></Link>):<p className="text-sm" style={{color:'var(--text-muted)'}}>{lang==='en'?'Explicit project links will appear here as notes are connected.':'노트에 프로젝트 연결 정보가 추가되면 여기에 표시됩니다.'}</p>}</div>
    </section>

    <section className="border-y" style={{borderColor:'var(--border)',backgroundColor:'var(--surface-hi)'}}><div className="mx-auto max-w-[1440px] px-5 py-12 sm:px-8 lg:px-16"><div className="grid gap-8 md:grid-cols-4">{channels.map((channel,i)=><Link key={channel.key} href={`${base}/${channel.href}`} className="group border-l pl-4" style={{borderColor:i===1?'var(--signal)':'var(--border-strong)'}}><div className="font-mono text-[9px] font-semibold tracking-[0.1em]" style={{color:i===1?'var(--signal)':'var(--accent)'}}>{channel.role}</div><div className="mt-3 text-xl font-semibold group-hover:text-[var(--accent)]" style={{color:'var(--text)'}}>{lang==='en'?channel.en:channel.ko}</div><ArrowUpRight className="mt-4 h-4 w-4" style={{color:'var(--text-faint)'}}/></Link>)}</div></div></section>

    <section className="mx-auto max-w-[1440px] px-5 py-14 sm:px-8 lg:px-16"><div className="grid gap-10 lg:grid-cols-[.58fr_1.42fr]"><div><div className="font-mono text-[10px] font-semibold tracking-[0.13em]" style={{color:'var(--accent)'}}>LATEST / WITH PROVENANCE</div><h2 className="mt-3 text-3xl font-semibold tracking-[-0.04em]" style={{color:'var(--text)'}}>{lang==='en'?'A stream of engineering records':'Engineering record의 흐름'}</h2><p className="mt-4 text-sm leading-6" style={{color:'var(--text-muted)'}}>{lang==='en'?'Each entry keeps its producing system visible so reading can move in both directions.':'각 글에 만들어낸 시스템을 남겨두어 글에서 시스템으로, 시스템에서 글로 양방향 탐색할 수 있습니다.'}</p></div><div className="divide-y" style={{borderColor:'var(--border)'}}>{notes.map((note,i)=><Link key={note.slug} href={`${base}/posts/${note.slug}`} className="group grid gap-3 py-6 first:pt-0 md:grid-cols-[52px_170px_1fr_auto] md:items-start" style={{borderColor:'var(--border)'}}><div className="font-mono text-[10px]" style={{color:'var(--text-faint)'}}>{String(i+1).padStart(2,'0')}</div><div className="font-mono text-[9px] uppercase tracking-[0.08em]" style={{color:'var(--accent)'}}>{note.projects?.length?note.projects.join(' · '):'WORKBENCH / UNLINKED'}</div><div><div className="text-xl font-semibold group-hover:text-[var(--accent)]" style={{color:'var(--text)'}}>{note.title}</div><p className="mt-2 text-sm leading-6" style={{color:'var(--text-muted)'}}>{note.description||(lang==='en'?'Engineering note from the workbench.':'Workbench에서 나온 engineering note.')}</p></div><ArrowUpRight className="hidden h-4 w-4 md:block" style={{color:'var(--text-faint)'}}/></Link>)}</div></div></section>

    <section className="border-t" style={{borderColor:'var(--border)'}}><div className="mx-auto max-w-[1440px] px-5 py-14 sm:px-8 lg:px-16"><div className="grid gap-6 lg:grid-cols-[.58fr_1.42fr]"><div><div className="font-mono text-[10px] font-semibold tracking-[0.13em]" style={{color:'var(--signal)'}}>TRACE RULE</div><h2 className="mt-3 text-3xl font-semibold tracking-[-0.04em]" style={{color:'var(--text)'}}>System → Decision / Incident → Note → Architecture / Release</h2></div><p className="text-base leading-8" style={{color:'var(--text-muted)'}}>{lang==='en'?'The goal is a traceable engineering record. A lesson should always have a path back to the context that produced it.':'목표는 추적 가능한 engineering record입니다. 교훈은 언제나 그것이 필요해진 시스템과 맥락으로 돌아갈 수 있어야 합니다.'}</p></div></div></section>
  </main>
}
