import Link from 'next/link';
import { ArrowUpRight } from 'lucide-react';
import { routing } from '@/i18n/routing';
import { getNotes, getProjects } from '@/lib/content';

export function generateStaticParams(){return routing.locales.map(locale=>({locale}))}

const channels=[
  {key:'notes',href:'notes',en:'Field Notes',ko:'필드 노트',role:'DECISIONS / INCIDENTS'},
  {key:'digest',href:'tech-digest',en:'Tech Digest',ko:'테크 다이제스트',role:'EXTERNAL SIGNALS'},
  {key:'talks',href:'seminars',en:'Talks',ko:'발표',role:'SHARED PRACTICE'},
  {key:'docs',href:'docs',en:'Docs',ko:'문서',role:'OPERATING KNOWLEDGE'},
] as const;

export default async function KnowledgePage({params}:{params:Promise<{locale:string}>}){
  const{locale}=await params;const lang=locale as 'ko'|'en';const base=lang==='en'?'/en':'/ko';const notes=getNotes(lang).slice(0,10);const projects=getProjects(lang);
  const linked=projects.map(project=>({project,count:notes.filter(note=>note.projects?.includes(project.slug)).length})).filter(item=>item.count>0).sort((a,b)=>b.count-a.count).slice(0,6);
  return <main>
    <section className="border-b" style={{borderColor:'var(--border)'}}><div className="mx-auto max-w-[1440px] px-5 py-14 sm:px-8 lg:px-16 lg:py-20"><div className="font-mono text-xs font-semibold tracking-[0.14em]" style={{color:'var(--accent)'}}>KNOWLEDGE / PROVENANCE GRAPH</div><h1 className="mt-5 max-w-5xl text-4xl font-semibold tracking-[-0.055em] sm:text-6xl" style={{color:'var(--text)'}}>{lang==='en'?<>Knowledge is more useful<br/>when its source is visible.</>:<>지식은 출처가 보일 때<br/>더 유용해집니다.</>}</h1><p className="mt-6 max-w-4xl text-base leading-8 sm:text-lg" style={{color:'var(--text-muted)'}}>{lang==='en'?'Notes, docs, talks and digests are connected back to the systems, decisions and failures that produced them. This is an engineering knowledge graph, not a content archive.':'노트, 문서, 발표와 다이제스트를 그것을 만들어낸 시스템·의사결정·실패와 다시 연결합니다. 콘텐츠 아카이브보다 engineering knowledge graph에 가깝게 구성합니다.'}</p></div></section>

    <section className="mx-auto max-w-[1440px] px-5 py-12 sm:px-8 lg:px-16"><div className="grid gap-8 lg:grid-cols-[.9fr_1.1fr]">
      <div><div className="font-mono text-[10px] font-semibold tracking-[0.13em]" style={{color:'var(--signal)'}}>SOURCE SYSTEMS</div><div className="mt-5 divide-y" style={{borderColor:'var(--border)'}}>{linked.length>0?linked.map(({project,count})=><Link key={project.slug} href={`${base}/projects/${project.slug}`} className="group grid grid-cols-[1fr_auto] gap-4 py-4 first:pt-0"><div><div className="text-lg font-semibold group-hover:text-[var(--accent)]" style={{color:'var(--text)'}}>{project.title}</div><div className="mt-1 font-mono text-[9px] uppercase tracking-[0.08em]" style={{color:'var(--text-faint)'}}>{project.tags.slice(0,3).join(' · ')}</div></div><div className="text-right"><div className="text-2xl font-semibold" style={{color:'var(--accent)'}}>{count}</div><div className="font-mono text-[9px]" style={{color:'var(--text-faint)'}}>LINKED NOTES</div></div></Link>):<p className="text-sm" style={{color:'var(--text-muted)'}}>{lang==='en'?'Explicit project links will appear here as notes are connected.':'노트에 프로젝트 연결 정보가 추가되면 여기에 표시됩니다.'}</p>}</div></div>
      <div className="rounded-[28px] border p-5 sm:p-6" style={{borderColor:'var(--border)',background:'linear-gradient(145deg,var(--surface),var(--surface-hi))'}}><div className="font-mono text-[10px] font-semibold tracking-[0.13em]" style={{color:'var(--accent)'}}>KNOWLEDGE TYPES</div><div className="mt-5 space-y-3">{channels.map((channel,i)=><Link key={channel.key} href={`${base}/${channel.href}`} className="group grid grid-cols-[90px_1fr_auto] items-center gap-3 rounded-2xl border p-4" style={{borderColor:'var(--border)',backgroundColor:'var(--surface)'}}><div className="font-mono text-[9px] font-semibold tracking-[0.1em]" style={{color:i===1?'var(--signal)':'var(--accent)'}}>{channel.role}</div><div className="font-semibold group-hover:text-[var(--accent)]" style={{color:'var(--text)'}}>{lang==='en'?channel.en:channel.ko}</div><ArrowUpRight className="h-4 w-4" style={{color:'var(--text-faint)'}}/></Link>)}</div></div>
    </div></section>

    <section className="border-y" style={{borderColor:'var(--border)',backgroundColor:'var(--surface-hi)'}}><div className="mx-auto max-w-[1440px] px-5 py-14 sm:px-8 lg:px-16"><div className="font-mono text-[10px] font-semibold tracking-[0.13em]" style={{color:'var(--accent)'}}>LATEST / WITH PROVENANCE</div><div className="mt-7 divide-y" style={{borderColor:'var(--border)'}}>{notes.map((note,i)=><Link key={note.slug} href={`${base}/posts/${note.slug}`} className="group grid gap-3 py-6 first:pt-0 md:grid-cols-[64px_1fr_1.1fr_auto] md:items-start" style={{borderColor:'var(--border)'}}><div className="font-mono text-[10px]" style={{color:'var(--text-faint)'}}>{String(i+1).padStart(2,'0')}</div><div><div className="text-xl font-semibold group-hover:text-[var(--accent)]" style={{color:'var(--text)'}}>{note.title}</div><div className="mt-2 font-mono text-[9px] uppercase tracking-[0.08em]" style={{color:'var(--accent)'}}>{note.projects?.length?note.projects.join(' · '):'WORKBENCH / UNLINKED'}</div></div><p className="text-sm leading-6" style={{color:'var(--text-muted)'}}>{note.description||(lang==='en'?'Engineering note from the workbench.':'Workbench에서 나온 engineering note.')}</p><ArrowUpRight className="hidden h-4 w-4 md:block" style={{color:'var(--text-faint)'}}/></Link>)}</div></div></section>

    <section className="mx-auto max-w-[1440px] px-5 py-14 sm:px-8 lg:px-16"><div className="grid gap-6 lg:grid-cols-[.7fr_1.3fr]"><div><div className="font-mono text-[10px] font-semibold tracking-[0.13em]" style={{color:'var(--signal)'}}>READING RULE</div><h2 className="mt-3 text-3xl font-semibold tracking-[-0.04em]" style={{color:'var(--text)'}}>{lang==='en'?'Follow the lesson back to the system.':'교훈에서 다시 시스템으로 돌아갑니다.'}</h2></div><p className="text-base leading-8" style={{color:'var(--text-muted)'}}>{lang==='en'?'A project should expose the notes, docs and talks it produced. A note should expose the system and architecture that made the lesson necessary. That two-way path is more valuable than a larger archive.':'프로젝트에서는 그 시스템에서 나온 노트·문서·발표를 보여주고, 노트에서는 그 교훈이 필요했던 시스템과 아키텍처로 돌아갈 수 있어야 합니다. 더 큰 아카이브보다 이 양방향 경로가 중요합니다.'}</p></div></section>
  </main>
}
